### ISSUE TITLE
Prefer FOUNDRY_RELEASE_URL to fetching by USERNAME/PASSWORD

### ISSUE THREAD

**Issue by hmqgg** [felddy/foundryvtt-docker#102]
# 🚀 Feature Proposal

Current behavior is that use `FOUNDRY_USERNAME`/`FOUNDRY_PASSWORD` (and `FOUNDRY_VERSION` if necessary) to fetch release URL even if you already set `FOUNDRY_RELEASE_URL` env var.
https://github.com/felddy/foundryvtt-docker/blob/70ead2b6f15a0dfe0bdb9037f90f03e189d8154b/src/entrypoint.sh#L69-L79

Requested feature is that always prefer `FOUNDRY_RELEASE_URL` if set, if it's invalid, use USERNAME/PASSWORD/VERSION to fetch S3 release URL, i.e.

```bash
 if [ "${FOUNDRY_RELEASE_URL:-}" ]; then 
   log "Using FOUNDRY_RELEASE_URL to download release." 
   s3_url="${FOUNDRY_RELEASE_URL}" 
 elif [[ "${FOUNDRY_USERNAME:-}" && "${FOUNDRY_PASSWORD:-}" ]]; then 
   log "Using FOUNDRY_USERNAME and FOUNDRY_PASSWORD to authenticate." 
   # CONTAINER_VERBOSE default value should not be quoted. 
   # shellcheck disable=SC2086 
   ./authenticate.js ${CONTAINER_VERBOSE+--log-level=debug} "${FOUNDRY_USERNAME}" "${FOUNDRY_PASSWORD}" "${cookiejar_file}" 
   # shellcheck disable=SC2086 
   s3_url=$(./get_release_url.js ${CONTAINER_VERBOSE+--log-level=debug} "${cookiejar_file}" "${FOUNDRY_VERSION}") 
 fi 
```

## Motivation

`FOUNDRY_RELEASE_URL` is a more detailed option, should be at higher priority than USERNAME/PASSWORD and especially because it explicitly specifies version other than the default VERSION argument or env var.

## Example

`docker run -e FOUNDRY_RELEASE_URL='https://dl/linux/fvtt.zip' -e FOUNDRY_USERNAME='myAccount' -e FOUNDRY_PASSWORD='myPassword' felddy/foundryvtt`

It should use `https://dl/linux/fvtt.zip` to download instead of fetching release URL by USERNAME/ACCOUNT.

## Pitch

Foundry VTT Docker behavior related.

**Comment by felddy** [comment]
I agree.  This is a good idea, and makes sense.  I'll try to work on this tomorrow.  
Thank you for the well-written proposal!
