### ISSUE TITLE
Auto accept EULA using enviroment variable

### ISSUE THREAD

**Issue by trivarialthea** [felddy/foundryvtt-docker#1062]
### Feature description

Add an environment variable that could be set to true/false and would auto accept the EULA.

### Motivation

Automated loading of existing worlds is borked, because of the EULA check getting reset on reboot.

### Example

N/A

### Pitch

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felddy** [comment]
Duplicate:
- https://github.com/felddy/foundryvtt-docker/issues/157

Solution:
- https://github.com/felddy/foundryvtt-docker/discussions/159#discussioncomment-480420
