### ISSUE TITLE
TURN server doesn't run

### ISSUE THREAD

**Issue by orangepeelbeef** [felddy/foundryvtt-docker#108]
# 🐛 Bug Report

When using the A/V service, a TURN server is supposed to startup and bind to udp:33478
I've enabled A/V in my world and no TURN server is spawned.

**Comment by felddy** [comment]
I suspect that your container is not [publishing](https://docs.docker.com/config/containers/container-networking/#published-ports) all of the ports required by Foundry's internal TURN server. 
See: https://foundryvtt.com/article/audio-video/#relay

By default these UDP ports are:`33478`, `49152`-`65535`

⚠️ A word of warning: Due to an long-standing bug in Docker, publishing large numbers of ports can lead **significant** performance issues.  See:  https://github.com/moby/moby/issues/11185

**Comment by orangepeelbeef** [comment]
I am publishing the ports, but the service isn't running/listening.  I even logged in with a root shell and looked around with netstat, it isn't there.

**Comment by orangepeelbeef** [comment]
I did find this note on that page:   
To disable Foundry's relay server, simply provide an empty list of turn configurations.

Does this container set blank turn config by default?  I am not passing any turnconfigs

**Comment by felddy** [comment]
I am not an expert on the Foundry internals, but I am pretty certain that the TURN server is not a separate process.  Foundry `v0.7.5` uses version `v0.0.6` of the [`node-turn`](https://github.com/Atlantis-Software/node-turn#readme) package.  I expect this follows the same single-threading model as the rest of node.  

This container does not set a value for`turnConfigs` in the `options.json` file unless you set the `FOUNDRY_TURN_CONFIGS` environment variable.  You can confirm this by looking at your `options.json` file.

If I start up the container and run a `netstat -lu` in it I do see the UDP TURN listening port listed: 

```console
/home/foundry # netstat -lu
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       
udp        0      0 127.0.0.11:53922        0.0.0.0:*                           
udp        0      0 0.0.0.0:33478           0.0.0.0:*                           
```

Are you seeing startup log entries showing that the RTC server started? 
```console
foundry_1  | FoundryVTT | 2020-11-05 22:16:31 | [info] EasyRTC: Starting EasyRTC Server (v2.0.5) on Node (v12.19.0)
foundry_1  | FoundryVTT | 2020-11-05 22:16:31 | [info] EasyRTC: EasyRTC Server Ready For Connections (v2.0.5)
foundry_1  | FoundryVTT | 2020-11-05 22:16:31 | [info] WebRTC Server started successfully
```

Did you enable Audio/Video in your world's configuration?
![image](https://user-images.githubusercontent.com/3229435/98322254-02b6ad00-1fb5-11eb-84ef-c887d8fd8dcc.png)

It would be helpful if you could post any log output, or configurations.

**Comment by orangepeelbeef** [comment]
Well, I blew the container away and rebuilt it and this time the TURN port is listening.  Not sure what was going on there, maybe something hosed up in the install process.  I used the exact same data directory and config files, so :shrug:   Sorry for the noise!

**Comment by felddy** [comment]
Glad you got it working.  Feel free to ping me if anything else comes up.
