### ISSUE TITLE
How to set data folder to write mode

### ISSUE THREAD

**Issue by trprado** [felddy/foundryvtt-docker#114]
# 💬 Questions and Help
Is it possible to set the data folder to rw permission? When I up my image, the permission of the data folder change to docker user, and it's not possible anymore to change unless I do it in Foundry.

**Comment by felddy** [comment]
You can configure the owner of the data folder and the container's process.
Please read the documentation about optional environment variables: 
https://github.com/felddy/foundryvtt-docker#optional

The variables that you want are `FOUNDRY_UID` and `FOUNDRY_GID`.
