### ISSUE TITLE
Modules folder indexing not working...

### ISSUE THREAD

**Issue by DanielRonnstam** [felddy/foundryvtt-docker#115]
# 💬 Questions and Help
Hi. When I upload modules directly to the Data folder on our Synology server, and then restart the synology, the new modules are not seen by Foundry. If I open a browser in Foundry and go to modules folder, the new modules are seen but they do not show up in the setup modules list. 

Please advise what to do, I don't know if this is a bug or not.

**Comment by felddy** [comment]
This does not seem to be a Docker container-specific issue.

Your best bet would be to ask in the [FoundryVTT Discord](https://discord.gg/foundryvtt) #toubleshooting channel.  It could be a FoundryVTT bug, and they'd be able to help.
