### ISSUE TITLE
License page empty on launch

### ISSUE THREAD

**Issue by Sandvich** [felddy/foundryvtt-docker#118]
Hi,
Not sure if this is a foundry issue or a docker image issue, so I figured I'd ask.
I've configured the image on my remote server as well as nginx, and when I connect I get redirected to the license page as expected. But there's no text on the page, and so no way to proceed. Did I do something wrong in the setup?

My launch command is:
```
sudo podman run \
        --env FOUNDRY_USERNAME='TTIO' \
        --env FOUNDRY_PASSWORD=<snipped> \
        --env FOUNDRY_ADMIN_KEY=<snipped> \
        --env FOUNDRY_HOSTNAME=<snipped> \
        --env FOUNDRY_PROXY_PORT=443 \
        --env FOUNDRY_PROXY_SSL=true \
        --publish 30000:30000/tcp \
        --volume foundry-vtt:/data \
        -d \
        --name foundry-vtt \
        felddy/foundryvtt:release
```

The NGINX file is a simple reverse proxy to port 30000, with a https redirect.

**Comment by Sandvich** [comment]
Welp, turns out I just didn't set up the proxy properly. I used your version of the proxy instead of the one I use for my own website and it worked xD

**Comment by felddy** [comment]
This is my favorite kind of issue!  (The ones that close themselves!) 
It sounds like it was a websocket proxy issue.  I'm glad you got it working. 🎉 
Happy Gaming!

**Comment by Sandvich** [comment]
Yup, exactly. My regular nginx proxy is intended for static pages, so it didn't have anything for sockets ^^;
