### ISSUE TITLE
Missing SSL support

### ISSUE THREAD

**Issue by raindropworks** [felddy/foundryvtt-docker#119]
# 💬 Questions and Help
I suspect this is less bug and more user error. I'm setting up FoundryVTT through docker, and using apache to handle the reverse proxy. I can connect and download and access resources, but in the log, when I enter the map I get the following error:

The WebRTC server was requested to start, but Foundry Virtual Tabletop is not running in SSL mode which is required.

When I'd been trying to do this without docker, I had successfully gotten past this after getting a cert for the subdomain it's using through letsencrypt. The cert is still valid, and all I had to do in apache was repoint where the proxy needed to look at (from another physical IP to localhost).

I'm thinking there's either a way I need to be able to pass information about the subdomain's ssl cert to the container or force it to use ssl mode, but i'm not sure how to do it

**Comment by felddy** [comment]
Please check the documentation for the environment variables: `FOUNDRY_PROXY_SSL`.  I believe this is what you are looking for.  See: https://github.com/felddy/foundryvtt-docker#optional

Additionally you may want to set `FOUNDRY_HOSTNAME`, and possibly `FOUNDRY_ROUTE_PREFIX`.

**Comment by raindropworks** [comment]
Thanks, I'm still relatively new to docker, so I was confused on the process, but adding `-e FOUNDRY_PROXY_SSL=true` to the docker run command (yes, I know docker compose is preferred) did seem to fix the SSL/WebRTC issue, and it seems after uploading a map I just had to exit the scene configuration and re-enter to select the image
