### ISSUE TITLE
Brainstorm: Preload modules/systems/worlds

### ISSUE THREAD

**Issue by hugoprudente** [felddy/foundryvtt-docker#12]
Hey Felddy.

I would like to brains storm with you something that I was thinking to add but I'm not sure if would make a lot of sense.

As we are using containers let's imagine that I have my 5gb assets folder or have a world world ready to play and would like to add to a clean server for any weird reason.

I was thinking a mechanism similar to what you do with foundry.zip now to incase some environment variables are passed with the URL of the location of the file it would fetch it and unzip on the proper directories o form the /data/Data.

This could also work for doing some git clones too so you don't need to go for the interface and select the mechanics and you can have a setup fully configured based on the environments variable and you could just "docker-compose up" or in may case "helm install foundry-vtt/" and couple seconds later everything is there.

What do you think about it?

Thanks.

**Comment by felddy** [comment]
I think this is a cool idea.  I'm not sure if it belongs in the docker container repo.  I have started an Ansible role project to install the container on a host: 

https://github.com/felddy/ansible-role-foundryvtt-docker

I think this role (or a role like it) would be the best place to implement something like that.  I'm going to think about this a bit more...

**Comment by hugoprudente** [comment]
Cool, I had some extra thought about it and know a cool way to resolve this also with my K8S chart taking advantage of Init containers.

Resolving this.
