### ISSUE TITLE
Permissions for /data not populating on host system properly?

### ISSUE THREAD

**Issue by raindropworks** [felddy/foundryvtt-docker#120]
# 💬 Questions and Help
When I set up my docker run command, I told it to use FOUNDRY_PUID and FOUNDRY_GUID as 1000, which is my personal user account. However, the web host that's handling proxy is running from a different user (normal linux www-data). Neither seems to be what the container is using as the mount point for the /data folder on the host system is shown as the following:

drwxr-xr-x  5        421        421 4096 Dec  1 20:30 foundryvtt

(yes, the user and group are showing as a right aligned '421' instead of normal left aligned alpha characters) I don't see anything like this in my console manager's user or group lists, but I'm sure it's something Docker related

While mildly annoying that I can't manipulate the directory without elevated permissions, I'm also thinking this could or could not have an issue with where I attempted to upload a map it uploads, but I can't seem to view it on the board (this could also be new user syndrome)

**Comment by felddy** [comment]
I'm sorry your having trouble with the container.  Please verify the accuracy of the environment variable names that you are setting.  To set the user id and group id you'll want: `FOUNDRY_UID`, and `FOUNDRY_GID`.  

See: https://github.com/felddy/foundryvtt-docker#optional

**Comment by raindropworks** [comment]
Thank you, that was a case of user error, having PUID and GUID instead of UID and GID. Purging the directory and fixing those values has it showing up right now
