### ISSUE TITLE
Add hotfix for 0.7.8

### ISSUE THREAD

**Issue by cs96and** [felddy/foundryvtt-docker#122]
# 🚀 Feature Proposal

There is a hotfix for 0.7.8 on the discord server.  Could this be added to the docker version of 0.7.8 please?

https://discord.com/channels/170995199584108546/784244473261588480/784490927212855317

**Comment by felddy** [comment]
Thank you for submitting this issue.

Once PR #123 is merged you can apply this patch to your containers by using either the `CONTAINER_PATCHES` or `CONTAINER_PATCH_URLS` environment variables.  
See: https://github.com/felddy/foundryvtt-docker#optional

If you are using a `docker-compose.yml` file, the patch can be applied using this environment variable configuration:
```yml
    environment:
      - CONTAINER_PATCH_URLS=
        https://raw.githubusercontent.com/felddy/foundryvtt-docker/develop/patches/hotfix_2020120401-0.7.8.sh
```

Thank you again for the submission, and let me know if there is anything else I can help you with.

**Comment by cs96and** [comment]
That was quick.  Thanks!

**Comment by felddy** [comment]
I was actually already writing it up when I saw you opened an issue.  I'm not that quick.  Just very good timing!
