### ISSUE TITLE
Container Stopped Working!

### ISSUE THREAD

**Issue by ratzofftyoya** [felddy/foundryvtt-docker#124]
# 💬 Questions and Help
Hi there! Not sure what happened. My container was working totally fine, including after pulling 0.7.8, but then it stopped working. On restart (including after removing image), I get the following in an endless loop.:

```console
Entrypoint | 2020-12-08 17:42:26 | [info] Starting felddy/foundryvtt container v0.7.8
Entrypoint | 2020-12-08 17:42:26 | [info] Foundry Virtual Tabletop 0.7.8 is installed.
Entrypoint | 2020-12-08 17:42:26 | [info] Not modifying existing installation license key.
Entrypoint | 2020-12-08 17:42:26 | [info] Setting data directory permissions.
Entrypoint | 2020-12-08 17:42:28 | [info] Starting launcher with uid:gid as foundry:foundry.
```

**Comment by felddy** [comment]
Sorry you're having this problem.  I haven't had this behavior reported before.  I'll see what I can do to help.

I'll need some additional information to help diagnose:

How are you running the Docker container?  e.g.; docker-compose, docker CLI, ...  

Could you please provide the container's configuration file, or command used to start it.

Please run this command:

```bash
docker inspect --format='{{range $k, $v := .Config.Labels}}
    {{- printf "%s = \"%s\"\n" $k $v -}} {{end}}' \
    felddy/foundryvtt:release
```

Paste the results here:

```console

```

Run the container with `CONTAINER_VERBOSE` set to `true`,and paste any useful
log output here:

```console

```

Make sure not to post any credentials, or other sensitive information.

**Comment by ratzofftyoya** [comment]
Thanks so much for your response! 
> 
> How are you running the Docker container? e.g.; docker-compose, docker CLI, ...

Running with docker-compose (as I was previously)
> 
> Could you please provide the container's configuration file, or command used to start it.
> 
Here is the compose script:
foundry:
    image: felddy/foundryvtt:latest
    init: true
    restart: "unless-stopped"
    networks:
      - traefik_proxy
    volumes:
      - type: bind
        source: /mnt/server/data/foundry/foundrydata
        target: /data
    environment:
      - FOUNDRY_PASSWORD=[mypassword]
      - FOUNDRY_USERNAME=[myusername]
      - CONTAINTER_VERBOSE=true
      - CONTAINER_PATCHES=/data/containerpatches //ADDED THIS AFTER PROBLEMS STARTED TO SEE IF IT MIGHT HELP
      - FOUNDRY_LICENSE_KEY=[mylicense key]  //ADDED THIS AFTER PROBLEMS STARTED TO SEE IF IT MIGHT HELP
    ports:
      - target: "30000"
        published: "30000"
        protocol: tcp
    labels: //THE SETUP BELOW IS IDENTICAL (BUT FOR THE "FOUNDRY" BITS, OF COURSE) TO MY OTHER WORKING CONTAINERS
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.foundry-rtr.entrypoints=https"
      - "traefik.http.routers.foundry-rtr.rule=HostHeader(`play.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.foundry-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.foundry-rtr.service=foundry-svc"
      - "traefik.http.services.foundry-svc.loadbalancer.server.port=30000"

> Please run this command:
> 
> ```shell
> docker inspect --format='{{range $k, $v := .Config.Labels}}
>     {{- printf "%s = \"%s\"\n" $k $v -}} {{end}}' \
>     felddy/foundryvtt:release
> ```
> 
> Paste the results here:
> 
com.foundryvtt.version = "0.7.8"
org.opencontainers.image.authors = "markf+github@geekpad.com"
org.opencontainers.image.created = "2020-12-04T17:18:28Z"
org.opencontainers.image.description = "An easy-to-deploy Dockerized Foundry Virtual Tabletop server."
org.opencontainers.image.licenses = "MIT"
org.opencontainers.image.revision = "d79ba13ebc52df9b3b0f189381789b934d5f26d7"
org.opencontainers.image.source = "https://github.com/felddy/foundryvtt-docker.git"
org.opencontainers.image.title = "foundryvtt-docker"
org.opencontainers.image.url = "https://github.com/felddy/foundryvtt-docker"
org.opencontainers.image.vendor = "Geekpad"
org.opencontainers.image.version = "0.7.8"



> Run the container with `CONTAINER_VERBOSE` set to `true`,and paste any useful
> log output here:
> 
Here is the full log until the endless loop starts:
    
Entrypoint | 2020-12-08 18:39:49 | [info] Starting felddy/foundryvtt container v0.7.8
Entrypoint | 2020-12-08 18:39:49 | [info] No Foundry Virtual Tabletop installation detected.
Entrypoint | 2020-12-08 18:39:49 | [info] Using FOUNDRY_USERNAME and FOUNDRY_PASSWORD to authenticate.
Authenticate | 2020-12-08 18:39:49 | [info] Requesting CSRF tokens from https://foundryvtt.com
Authenticate | 2020-12-08 18:39:50 | [info] Logging in as: [REDACTED]
Authenticate | 2020-12-08 18:39:52 | [info] Successfully logged in as: [REDACTED]
Entrypoint | 2020-12-08 18:39:52 | [info] Using authenticated credentials to download release.
ReleaseURL | 2020-12-08 18:39:52 | [info] Fetching S3 pre-signed release URL for 0.7.8...
Entrypoint | 2020-12-08 18:39:53 | [info] Downloading Foundry Virtual Tabletop release.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0  115M    0 68213    0     0  48139      0  0:41:46  0:00:01  0:41:45 48105
  0  115M    0  882k    0     0   351k      0  0:05:34  0:00:02  0:05:32  351k
  6  115M    6 8033k    0     0  2364k      0  0:00:49  0:00:03  0:00:46 2364k
 19  115M   19 22.7M    0     0  5192k      0  0:00:22  0:00:04  0:00:18 5191k
 30  115M   30 34.9M    0     0  6660k      0  0:00:17  0:00:05  0:00:12 7314k
 43  115M   43 49.6M    0     0  7937k      0  0:00:14  0:00:06  0:00:08  9.9M
 53  115M   53 62.1M    0     0  8627k      0  0:00:13  0:00:07  0:00:06 12.5M
 66  115M   66 76.1M    0     0  9314k      0  0:00:12  0:00:08  0:00:04 13.7M
 77  115M   77 88.9M    0     0  9706k      0  0:00:12  0:00:09  0:00:03 13.5M
 88  115M   88  102M    0     0   9.8M      0  0:00:11  0:00:10  0:00:01 13.4M
100  115M  100  115M    0     0  10.1M      0  0:00:11  0:00:11 --:--:-- 13.4M
Entrypoint | 2020-12-08 18:40:04 | [info] Installing Foundry Virtual Tabletop 0.7.8
Entrypoint | 2020-12-08 18:40:06 | [info] Using CONTAINER_PATCHES: /data/containerpatches
Entrypoint | 2020-12-08 18:40:06 | [warn] Container patches directory not found.
Entrypoint | 2020-12-08 18:40:06 | [info] Not modifying existing installation license key.
Entrypoint | 2020-12-08 18:40:06 | [info] Setting data directory permissions.
Entrypoint | 2020-12-08 18:40:08 | [info] Starting launcher with uid:gid as foundry:foundry.
Entrypoint | 2020-12-08 18:40:09 | [info] Starting felddy/foundryvtt container v0.7.8
Entrypoint | 2020-12-08 18:40:09 | [info] Foundry Virtual Tabletop 0.7.8 is installed.
Entrypoint | 2020-12-08 18:40:09 | [info] Not modifying existing installation license key.
Entrypoint | 2020-12-08 18:40:09 | [info] Setting data directory permissions.
Entrypoint | 2020-12-08 18:40:12 | [info] Starting launcher with uid:gid as foundry:foundry.
Entrypoint | 2020-12-08 18:40:13 | [info] Starting felddy/foundryvtt container v0.7.8
Entrypoint | 2020-12-08 18:40:13 | [info] Foundry Virtual Tabletop 0.7.8 is installed.
Entrypoint | 2020-12-08 18:40:13 | [info] Not modifying existing installation license key.
Entrypoint | 2020-12-08 18:40:13 | [info] Setting data directory permissions.
Entrypoint | 2020-12-08 18:40:15 | [info] Starting launcher with uid:gid as foundry:foundry.
Entrypoint | 2020-12-08 18:40:16 | [info] Starting felddy/foundryvtt container v0.7.8
Entrypoint | 2020-12-08 18:40:16 | [info] Foundry Virtual Tabletop 0.7.8 is installed.
Entrypoint | 2020-12-08 18:40:16 | [info] Not modifying existing installation license key.
Entrypoint | 2020-12-08 18:40:16 | [info] Setting data directory permissions.
Entrypoint | 2020-12-08 18:40:19 | [info] Starting launcher with uid:gid as foundry:foundry.
Entrypoint | 2020-12-08 18:40:20 | [info] Starting felddy/foundryvtt container v0.7.8
Entrypoint | 2020-12-08 18:40:20 | [info] Foundry Virtual Tabletop 0.7.8 is installed.
Entrypoint | 2020-12-08 18:40:20 | [info] Not modifying existing installation license key.
Entrypoint | 2020-12-08 18:40:20 | [info] Setting data directory permissions.



Note also that I've recursively chmodded the data folder to 0777.

**Comment by felddy** [comment]
You've got a typo in your environment variables: `CONTAINTER_VERBOSE` should be `CONTAINER_VERBOSE`.

After fixing that could you repost the logs.  You should see `[debug]` entries.
