### ISSUE TITLE
Prevent entrypoint.sh from crawling mount points in data folder

### ISSUE THREAD

**Issue by zdaar** [felddy/foundryvtt-docker#145]
# 🚀 Feature Proposal

adding the `-xdev` flag to the find command to skip setting permissions on a mounted point 
## Motivation

Whenever I create a container with the image the find command in `entrypoint.sh` user for setting permissions will crawl my nfs mounted points that I use for assets, destroying all of the permissions on the drive along with hanging for a very long time while it does so. Some people like me map assets on a network drive and mount it at the root folder so it is accessible to all worlds within a foundry instance. In my case in `/data/assets`. This is not desirable.

## Example
This is the command it runs : 
https://github.com/felddy/foundryvtt-docker/blob/8c0e0dce2df9b233a46bbfec7c9bb21166ad1843/src/entrypoint.sh#L212

This is the proposed change : 
```shell
find /data -regex "${CONTAINER_PRESERVE_OWNER:-}" -xdev -prune -o -exec chown "${FOUNDRY_UID:-foundry}:${FOUNDRY_GID:-foundry}" {} +
```

## Pitch
I believe the most common usecase for mounting a folder inside the /data folder is to mount network storage with assets.
I believe this will not impact regular users and prevent having to maintain a patch for the issue.

Thanks for considering it

**Comment by felddy** [comment]
Thank you for the thoughtful proposal. I understand your use case.  
Please take a look at PR #127 as it is very similar. 

I think the solution to this issue is to set `CONTAINER_PRESERVE_OWNER` environment variable as documented here: https://github.com/felddy/foundryvtt-docker#optional

Let me know if this solution addresses your issue.

**Comment by zdaar** [comment]
Hello felddy,

Thanks for your reply. This fixed my issue, permissions are preserved for the value path specified in the environement variable.
Much appreciated !
