### ISSUE TITLE
Add flag to use command line option --ignore-gpu-blacklist

### ISSUE THREAD

**Issue by cpcodes** [felddy/foundryvtt-docker#154]
# 🚀 Feature Proposal

Per the optimization recommendations at https://prezi.com/view/Wpq1WQv92LC1KNwwAEyG/, put together by Anathema, this can force Foundry to use Hardware acceleration when it might otherwise be attempting to use software rendering, thus improving performance. This would be optional, and it could also cause problems with unsupported graphics cards.

## Motivation

Was double-checking my setup and could not verify that this was being performed in the container.

## Example

Set the FOUNDRY_IGNORE_GPU_BLACKLIST env variable to true and it will add the --ignore-gpu-blacklist flag to the command line when launching Foundry.

## Pitch

Recommended best practice for troubleshooting poor performance by the community lead for Foundry?

**Comment by felddy** [comment]
Thank you for opening an issue for this.  

From my quick read on this the `--ignore-gpu-blacklist` is a flag that would be passed to the Chromium browser.   Since this is not a flag that would be passed to Foundry I do not think it is applicable to the container.  That is, this container does not run a browser (client) , it only runs the web application (server) side of things.  

When I get a chance I'll double check this.

**Comment by felddy** [comment]
If you enter `chrome://flags/#ignore-gpu-blocklist` into Chrome you will see the following documentation:

## Override software rendering list ##
```
Overrides the built-in software rendering list and enables GPU-acceleration on unsupported system configurations.
– Mac, Windows, Linux, Chrome OS, Android
```

So, I'm pretty confident that this is a Chrome flag.  Please let me know if you have some information to the contrary.

**Comment by felddy** [comment]
Closing due to non-response.

**Comment by cpcodes** [comment]
All I have to offer are these screen shots from the previously linked presentation. Your argument makes sense, but they mention that in another tip (Prezi Foundry slide BHA), so I assumed that they were different things.
![Prezi Foundry slide BHA](https://user-images.githubusercontent.com/30065410/110670719-8f02f780-8182-11eb-9fb3-83a5b67d46b4.png)
![Prezi Foundry slide FHA](https://user-images.githubusercontent.com/30065410/110670730-90ccbb00-8182-11eb-9a50-da1f21a8eecf.png)
