### ISSUE TITLE
Flag to bypass "Setting data directory permissions" step

### ISSUE THREAD

**Issue by adam8797** [felddy/foundryvtt-docker#158]
# 🚀 Feature Proposal

I would like a flag that would have the startup script skip the chmod of the data directory on startup

## Motivation

I mount the data directories from NFS, and I've already set the proper permissions on all files. With hundreds upon hundreds of shared files, it takes about three to four minutes on my saves

## Example

On environments where you know the uid/gid of the files ahead of time, you could opt to skip this stick

## Pitch

Makes restarting containers, or setting up new containers with shared data much faster, and for minimal effort

**Comment by adam8797** [comment]
This is a very quick addition I believe. I can't this weekend, but I imagine I'll be able to send a PR your way by next week. I'm thinking a simple environment variable like `FOUNDRY_SKIP_FILE_PERMS` set to `true` would do the trick. If its not provided, functionality doesn't change from current.

**Comment by felddy** [comment]
@adam8797 good news! I think there is a feature that'll do this for you already.   Check out the [`CONTAINER_PRESERVE_OWNER`](https://github.com/felddy/foundryvtt-docker#optional) environment variable and discussion #153 .

I think you'll want to set  `CONTAINER_PRESERVE_OWNER` to `/data` to get the functionality you're proposing in your flag. 

I truly appreciate your offer to implement this.

**Comment by adam8797** [comment]
doh! This is very much a "read the docs" type issue.

Thanks @felddy! I'll implement using that env variable.
