### ISSUE TITLE
Support email addresses in FOUNDRY_USERNAME environment variable

### ISSUE THREAD

**Issue by felddy** [felddy/foundryvtt-docker#16]
# 🚀 Feature Proposal

Support using an email address as the `FOUNDRY_USERNAME`. 

## Motivation

Reported by: @Corvimae 

It is possible to log in to foundryvtt.com using your email address.  But when the `download_release.js` helper util goes to fetch the license key, it will error out as it is trying to build a path with the username. 

We could document that `FOUNDRY_USERNAME` is not supposed to be an email address but user's don't read the docs, and it will be simpler in the long run to allow this to happen. 

## Example

```
FOUNDRY_USERNAME=lemmy@motorhead.com
FOUNDRY_PASSWORD=yourmom
```

## Pitch

Make the user's lives easier.  Things are hard enough nowadays.

**Comment by Kenidashi** [comment]
As a note, it seems that the username should be lowercase when fetching the license key. I submitted a username that had a capital letter at the beginning of it, and I hit the error point I'm guessing @Corvimae also hit. Converting that character to lowercase resolved the error. That being said, my displayed username on the main site at several points still has the capital letter in it.

**Comment by felddy** [comment]
Thanks for the follow up.  I was able to reproduce both issues:
* mix-case usernames will cause a `Not Found` response.
* email addresses are accepted as a username, but cause the same `Not Found` response.

Both of these stem from how the `LICENSE_URL` is crafted.  The mix-case is an easy fix.  The resolution of email address to username will take a little extra work.  

I'll open a draft PR to work on this now.  Thank you again for the report!
