### ISSUE TITLE
Configuration Changes Won't Save

### ISSUE THREAD

**Issue by JBlocklove** [felddy/foundryvtt-docker#215]
# 🐛 Bug Report

When I try to make configuration changes on the setup page (default world, admin password, etc) they don't seem to save. The container restarts but nothing changes once it's back up.

## To Reproduce

- Start up a container
- Change the default world or another value in the "Configuration" pane
- Save the change
- Re-enter the "Configuration" pane after the container reboots

## Expected behavior

For the changed values to stay changed

## Any helpful log output

Please run this command:

```bash
docker inspect --format='{{range $k, $v := .Config.Labels}}
    {{- printf "%s = \"%s\"\n" $k $v -}} {{end}}' \
    felddy/foundryvtt:latest
```

Paste the results here:

```console
com.foundryvtt.version = "0.8.6"
org.opencontainers.image.authors = "markf+github@geekpad.com"
org.opencontainers.image.created = "2021-05-31T15:02:59Z"
org.opencontainers.image.description = "An easy-to-deploy Dockerized Foundry Virtual Tabletop server."
org.opencontainers.image.licenses = "MIT"
org.opencontainers.image.revision = "44f414116ddaf1fb9ba2d8c9f6ebf1bb79fa34a0"
org.opencontainers.image.source = "https://github.com/felddy/foundryvtt-docker.git"
org.opencontainers.image.title = "foundryvtt-docker"
org.opencontainers.image.url = "https://github.com/felddy/foundryvtt-docker"
org.opencontainers.image.vendor = "Geekpad"
org.opencontainers.image.version = "0.8.6"
```

Run the container with `CONTAINER_VERBOSE` set to `true`,and paste any useful
log output here:

I don't see any log output that would relate to this. `debug.log` doesn't seem to contain anything related to this issue and `error.log` only seems to have errors from some of my modules.

**Comment by felddy** [comment]
Sorry you're running into this.  I should document it more clearly in the `README` how the configurations are handled in the container.  

When the container starts up the `options.json` file that stores FoundryVTT's configurations is generated using the [optional environment variables](https://github.com/felddy/foundryvtt-docker#optional). 

Normally, if you make changes within the web UI, they will not persist when the container is restarted.  To change this behavior and have the `options.json` preserved set the `CONTAINER_PRESERVE_CONFIG` environment variable to `true`.  

From the `README`:

| Name  | Purpose | Default |
|-------|---------|---------|
| `CONTAINER_PRESERVE_CONFIG` | Normally new `options.json` and `admin.txt` files are generated by the container at each startup.  Setting this to `true` prevents the container from modifying these files when they exist.  If they do not exist, they will be created as normal. | `false` |

Let me know if this addresses your issue.

**Comment by JBlocklove** [comment]
Gotcha. Yep, all works well now. I had thought something about the additional env variables was messed up because I did have an admin password set in those and it wasn't working, but it turns out that I had a typo in there as well. Fixed that and it all works as planned. Thanks!
