### ISSUE TITLE
Cross origin error in current release version

### ISSUE THREAD

**Issue by Ganayan** [felddy/foundryvtt-docker#217]
# 🐛 Bug Report

After entering the admin password, the website crashed with a cross-origin error.
## To Reproduce

Update to the current release version.
Try to activate VTT using the correct admin password.

## Expected behavior

Entering the correct credentials should lead me to my vtt setup.

**Comment by felddy** [comment]
Thank you for reporting this. 

This has been determined to be a FoundryVTT 0.8.6 issue. 
See discussion #210 
And the upstream issue: https://gitlab.com/foundrynet/foundryvtt/-/issues/5263
