### ISSUE TITLE
Include Node14 js in the image

### ISSUE THREAD

**Issue by krusty4president** [felddy/foundryvtt-docker#222]
# 🚀 Feature Proposal

A clear and concise description of what the feature is.

## Motivation

Please include the Node 14 js in the image so we can continue run the image on Synology NAS  drives. Thanks

## Example

Please provide an example for how this feature would be used.

## Pitch

Why does this feature belong in this project?

**Comment by felddy** [comment]
The current version of Node.js used by the container is 14:
https://github.com/felddy/foundryvtt-docker/blob/848328f046c2175e36020639adc2b458de281d9a/Dockerfile#L36

This was implemented and merged in PR #142 on January 7th, 2021 to address issue #141.

You should see entries similar to this in the container logs:
```console
foundry_1  | FoundryVTT | 2021-06-23 16:18:30 | [info] Running on Node.js - Version 14.16.0
foundry_1  | FoundryVTT | 2021-06-23 16:18:30 | [info] Foundry Virtual Tabletop - Version 0.8.7
```

What version of the container are you running, and what version of Node.js are you seeing?
