### ISSUE TITLE
Download/Installing Foundry during the build stage.

### ISSUE THREAD

**Issue by hugoprudente** [felddy/foundryvtt-docker#23]
Hi Felddy,

I saw that you have changed the behaviour of the image pulling for the .js alternative and with that dropped the capability of a fetch-install during the build using the old command.

```
docker-compose build \
--build-arg USERNAME='user' \
--build-arg PASSWORD='mYPa$$'
```

Do you plan to re-add it in any other way?

I'm checking too ensure that the K8S chart reflects how it works and I would like to avoid asking for the users to provide passwords on the vales.yaml or parameter and deliver it as a environment variable plain text to the container during it's execution, that it's not safe.

**Comment by felddy** [comment]
Hey Hugo.  I understand your concerns about credential passing via environment variable at runtime.  I do plan on re-adding the functionality to pre-build in a Foundry release to the image.  It was important for me to support a simpler use case for the community using `docker pull`, and the associated Ansible role: https://github.com/felddy/ansible-role-foundryvtt-docker

The end goal of this container is to be a fully-functional FoundryVTT instance from `pull`, without the need to download the release at runtime.  So I will need the mode you're requesting as well.  I've already built in some of the functionality to do this.  e.g.; the startup release version check.

I'm not sure what the timing of this will be.  I'll try to get to it as soon as I can.  It shouldn't be a heavy lift.

Thanks again for your contributions!

**Comment by felddy** [comment]
@hugoprudente ... let me know if this solution works for you.  

See: 
https://github.com/felddy/foundryvtt-docker#pre-installed-release-builds

**Comment by hugoprudente** [comment]
Hi @felddy yes, it works as a charm!

Resolving this!

Thanks a million.
