### ISSUE TITLE
Avoid trying to chown read-only folders

### ISSUE THREAD

**Issue by caewok** [felddy/foundryvtt-docker#243]
# 🐛 Bug Report

I set up a mount to my Backblaze S3 drive using s3fs, which in turn is mounted in the docker image. I am using this to store certain very large images (e.g., from map modules) to avoid having to use a larger VM storage. (I know that Foundry can see S3 drives, but in some cases this seems to be the easier solution for more complex map modules.) 

This works well, except that this docker image attempts to chown the read-only mounted drive folder, with no success. This causes it to throw an error in the log on every single image file, and as a result it takes forever to actually start the docker instance. All the errors are of the form:

> chown: /data/Data/modules/.../image.png: I/O error

Pretty sure the problem originates in the [`entrypoint.sh` file](https://github.com/felddy/foundryvtt-docker/blob/38cafe9a4342cb790ea97e944ded2aeca486d8a5/src/entrypoint.sh#L225).

As far as I can tell, the read-only folder does not cause any actual problems within Foundry. Obviously, re-installing or updating the module might break the folder mount, but if so, that is easily fixed on my end.

## To Reproduce

- Make a folder in Data/modules read-only
- Then start the docker image.

## Expected behavior

I understand that you probably have good reason for verifying ownership of files within the docker image. But maybe ignore read-only files and directories? Or de-bounce the errors so that only the first one is logged? 

## Any helpful log output

Please run this command:

```bash
docker inspect --format='{{range $k, $v := .Config.Labels}}
    {{- printf "%s = \"%s\"\n" $k $v -}} {{end}}' \
    felddy/foundryvtt:latest
```

Paste the results here:

```console
com.foundryvtt.version = "0.8.9"
org.opencontainers.image.authors = "markf+github@geekpad.com"
org.opencontainers.image.created = "2021-08-17T17:23:17Z"
org.opencontainers.image.description = "An easy-to-deploy Dockerized Foundry Virtual Tabletop server."
org.opencontainers.image.licenses = "MIT"
org.opencontainers.image.revision = "38cafe9a4342cb790ea97e944ded2aeca486d8a5"
org.opencontainers.image.source = "https://github.com/felddy/foundryvtt-docker.git"
org.opencontainers.image.title = "foundryvtt-docker"
org.opencontainers.image.url = "https://github.com/felddy/foundryvtt-docker"
org.opencontainers.image.vendor = "Geekpad"
org.opencontainers.image.version = "0.8.9"
```

**Comment by felddy** [comment]
Take a look at the documentation for `CONTAINER_PRESERVE_OWNER` in the [README](https://github.com/felddy/foundryvtt-docker#optional).  I think this feature will address your concerns.  

See also: 
 - https://github.com/felddy/foundryvtt-docker/discussions/153
 - https://github.com/felddy/foundryvtt-docker/discussions/168

Let me know if this helps.

**Comment by caewok** [comment]
Yep, that addresses it! Sorry I missed it in the README.
