### ISSUE TITLE
Out of memory error with FoundryVTT 8.9 when importing large assets

### ISSUE THREAD

**Issue by xholicka** [felddy/foundryvtt-docker#257]
# 🐛 Bug Report

Importing large assets (one 10MB file) from compendium to gameworld crashes docker and restarts container(s).

Docker logs: 
```console
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
Aborted (core dumped)
```

## To Reproduce

Install this Addon:
https://pyramking.gitlab.io/foundry-adventure-modules/countscrypt/mS3CsUxba11s/module.json

Try to import it to your game world on a system with low memory (1GB or less). In my case Raspberry 3B+.
Import of Items will fail.

## Expected behavior

Import of items will pass without any issue.

## Any helpful log output

By adding `cgroup_enable=memory swapaccount=1` to `/boot/cmdline.txt` on my RPI I got rid of these warnings from `docker info`

```console
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory TCP limit support
WARNING: No oom kill disable support
```

Please run this command:

```bash
docker inspect --format='{{range $k, $v := .Config.Labels}}
    {{- printf "%s = \"%s\"\n" $k $v -}} {{end}}' \
    felddy/foundryvtt:latest
```

Paste the results here:

```console
com.docker.compose.config-hash = "372e779b491213a5f5eea06dc4688217184eb92a4a4edc1b5a8e317fc782fbdb"
com.docker.compose.container-number = "1"
com.docker.compose.oneoff = "False"
com.docker.compose.project = "docker"
com.docker.compose.project.config_files = "docker-compose.yml"
com.docker.compose.project.working_dir = "/home/pi/docker"
com.docker.compose.service = "foundry"
com.docker.compose.version = "1.29.2"
com.foundryvtt.version = "0.8.9"
org.opencontainers.image.authors = "markf+github@geekpad.com"
org.opencontainers.image.created = "2021-08-17T17:23:17Z"
org.opencontainers.image.description = "An easy-to-deploy Dockerized Foundry Virtual Tabletop server."
org.opencontainers.image.licenses = "MIT"
org.opencontainers.image.revision = "38cafe9a4342cb790ea97e944ded2aeca486d8a5"
org.opencontainers.image.source = "https://github.com/felddy/foundryvtt-docker.git"
org.opencontainers.image.title = "foundryvtt-docker"
org.opencontainers.image.url = "https://github.com/felddy/foundryvtt-docker"
org.opencontainers.image.vendor = "Geekpad"
org.opencontainers.image.version = "0.8.9"

```

What solved the issue for me was adding `--max-old-space-size=512` to node command starting foundry. I chose 512MB because it was still a little bit less than available memory on my device.

After adding this and rebuilding the foundry docker image the import of Items assets completed fine and everything seems to work normal. Still I would like someone more tech savvy to explain to me how this docker vs node memory management works. 
And probably fix this for others using this image on lowend devices or in cloud.

**Comment by xholicka** [comment]
From: 
https://developer.ibm.com/articles/nodejs-memory-management-in-container-environments/

When Node.js applications are running within containers with memory limits set (using the `--memory` option for docker or any other flags with your orchestration system), use the `--max-old-space-size` option to ensure that Node knows its limit and that the set value is smaller than the container limit.

When Node.js applications are running within containers, specify the memory capacity in accordance with the peak active memory usage of the application (if container memory can be adjusted).

**Comment by xholicka** [comment]
The mentioned module 

https://pyramking.gitlab.io/foundry-adventure-modules/countscrypt/mS3CsUxba11s/module.json

was "repaired" by author in version 1.1.1 so this doesnt happen anymore.

**Comment by felddy** [comment]
Closing as it was repaired by the Foundry plugin author.
