### ISSUE TITLE
Add package-lock.json file to the repository

### ISSUE THREAD

**Issue by crogonint** [felddy/foundryvtt-docker#262]
# 🐛 Bug Report

npm notice created a lockfile as `package-lock.json`. You should commit this file.
When I looked it up, I got references saying that it needs to added to the git??

```console
docker build \
  --build-arg FOUNDRY_USERNAME='<your_username>' \
  --build-arg FOUNDRY_PASSWORD='<your_password>' \
  --build-arg VERSION=0.8.9 \
  --tag felddy/foundryvtt:0.8.9 \
  https://github.com/felddy/foundryvtt-docker.git#develop
```

**Comment by felddy** [comment]
You are correct.  It is a best-practice to commit the `package-lock.json` file to the repository:

https://docs.npmjs.com/cli/v8/configuring-npm/package-lock-json

I will include one for the next release.

**Comment by felddy** [comment]
`package-lock.json` was added to the repo on December 7th, 2020.

https://github.com/felddy/foundryvtt-docker/commits/develop/package-lock.json
