### ISSUE TITLE
"Fatal error in , line 0 ... unreachable code" on Raspberry Pi

### ISSUE THREAD

**Issue by dany-jorge** [felddy/foundryvtt-docker#268]
# 🐛 Bug Report #

Image for v9.238 will not run on RPI.  Always stops with error ""Fatal error in , line 0 ... unreachable code".  Container will continuously restart.

## To Reproduce ##

Running on Linux raspberrypi 5.10.63-v7l+ arm71

Pulled same image on Docker for Windows and starts as expected.
Spun up Node directly on RPI  and was able to run Foundry normally.
Downgraded the container's image to  previous version 0.8.9 then starts normally.

- On Raspberry Pi ,  pull the v9 release image
- Then create new docker container with the image
- Run the container

## Expected behavior ##

Should start normally.

## Any helpful log output ##

Please run this command:

```bash
docker inspect --format='{{range $k, $v := .Config.Labels}}
    {{- printf "%s = \"%s\"\n" $k $v -}} {{end}}' \
    felddy/foundryvtt:latest
```

Paste the results here:

```console
com.foundryvtt.version = "9.238"
org.opencontainers.image.authors = "markf+github@geekpad.com"
org.opencontainers.image.created = "2021-12-21T03:59:28Z"
org.opencontainers.image.description = "An easy-to-deploy Dockerized Foundry Vir                                                                                                             tual Tabletop server."
org.opencontainers.image.licenses = "MIT"
org.opencontainers.image.revision = "7bddeabf3c46218827e5f55c6c18302a5676101b"
org.opencontainers.image.source = "https://github.com/felddy/foundryvtt-docker.g                                                                                                             it"
org.opencontainers.image.title = "foundryvtt-docker"
org.opencontainers.image.url = "https://github.com/felddy/foundryvtt-docker"
org.opencontainers.image.vendor = "Geekpad"
org.opencontainers.image.version = "9.238.0"

```

Run the container with `CONTAINER_VERBOSE` set to `true`,and paste any useful
log output here:

```console
Creating network "test_default" with the default driver
Creating test_foundry_1 ... done
Attaching to test_foundry_1
foundry_1  | Entrypoint | 2071-06-29 04:01:36 | [debug] Timezone set to: UTC
foundry_1  | Entrypoint | 2071-07-13 07:05:04 | [info] Starting felddy/foundryvtt container v9.238.0
foundry_1  | Entrypoint | 2071-05-02 10:12:48 | [debug] CONTAINER_VERBOSE set.  Debug logging enabled.
foundry_1  | Entrypoint | 2071-06-05 11:08:16 | [info] No Foundry Virtual Tabletop installation detected.
foundry_1  | Entrypoint | 2071-05-13 17:00:16 | [info] Using FOUNDRY_USERNAME and FOUNDRY_PASSWORD to authenticate.
foundry_1  |
foundry_1  |
foundry_1  | #
foundry_1  | # Fatal error in , line 0
foundry_1  | # unreachable code
foundry_1  | #
foundry_1  | #
foundry_1  | #
foundry_1  | #FailureMessage Object: 0xbec1153c
foundry_1  | Trace/breakpoint trap (core dumped)

```

**Comment by felddy** [comment]
Weird, looks like a NodeJS crash. 

I also run my instance on a Raspberry Pi, but I am not seeing this.  I'm dumping my machines info below.  I'll do some Node research and see what I can dig up. 

In the meantime let's see if `node` can run at all.  Try executing this:
```console
docker run --rm -it node:16-alpine node --version
```

My machine info:

```console
$ uname -a 
Linux appa 5.10.63-v8+ #1459 SMP PREEMPT Wed Oct 6 16:42:49 BST 2021 aarch64 GNU/Linux
$ uname -m
aarch64
$ cat /etc/issue.net 
Debian GNU/Linux 11
$ free -h
               total        used        free      shared  buff/cache   available
Mem:           7.6Gi       3.8Gi       1.1Gi        31Mi       2.7Gi       3.7Gi
Swap:           99Mi        10Mi        89Mi
$ docker --version
Docker version 20.10.5+dfsg1, build 55c4c88
```

**Comment by dany-jorge** [comment]
Here is my machine info:
```console
pi@raspberrypi:~ $ docker run --rm -it node:16-alpine node --version
v16.13.1
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 5.10.63-v7l+ #1496 SMP Wed Dec 1 15:58:56 GMT 2021 armv7l GNU/                                                   Linux
pi@raspberrypi:~ $ uname -m
armv7l
pi@raspberrypi:~ $ cat /etc/issue.net
Raspbian GNU/Linux 10
pi@raspberrypi:~ $ free -h
              total        used        free      shared  buff/cache   available
Mem:          3.7Gi       430Mi       989Mi       152Mi       2.4Gi       3.1Gi
Swap:          99Mi          0B        99Mi
pi@raspberrypi:~ $ docker --version
Docker version 20.10.12, build e91ed57
```

**Comment by felddy** [comment]
@dany-jorge were you test run `node --version` using the command above?

**Comment by dany-jorge** [comment]
First command I ran.

```console
pi@raspberrypi:~ $ docker run --rm -it node:16-alpine node --version
v16.13.1
```
Continued testing and have some new clues.
I am running Raspbian GNU/Linux 10 based on Debian Buster
As an additional test I swapped out the OS on my RPI and installed the new OS based on Debian Bullseye to match your Linux 11. After upgrading the OS I was able to run the image without problems.
So appears to be specific to Debian Buster

**Comment by vehrka** [comment]
Hi, same problem here

Also running Linux 10

```
$ docker run --rm -it node:16-alpine node --version
v16.13.1
$ uname -a 
Linux cheraserver 5.10.17-v8+ #1421 SMP PREEMPT Thu May 27 14:01:37 BST 2021 aarch64 GNU/Linux
$ uname -m
aarch64
$ cat /etc/issue.net 
Raspbian GNU/Linux 10
$ free -h
               total        used        free      shared  buff/cache   available
Mem:           3.7Gi       663Mi       205Mi        223Mi       2.9Gi       2.8Gi
Swap:           99Mi        1.0Mi        98Mi
$ docker --version
Docker version 20.10.8, build 3967b7d
```

I will try to update the OS

**Comment by vehrka** [comment]
I can also confirm that after updating to Bullseye the docker runs OK

**Comment by orangetruth** [comment]
Updating to Bullseye also fixed this issue for me

**Comment by yoshikidneo** [comment]
I'm currently using Twister OS for my Pi that hosts Foundry and version 9 does not work. Currently Twister OS is still on Linux 10. Any chance this will get resolved or would I need to change OS to get Foundry v9?

**Comment by felddy** [comment]
The root cause is:
- https://github.com/nodejs/docker-node/issues/1477

See also: 
- https://github.com/felddy/foundryvtt-docker/issues/196
- https://github.com/felddy/foundryvtt-docker/discussions/325
- https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.13.0#time64_requirements

Mitigations:
- Multiple users have reported that updating to Debian 11 or its analogs solved this issue.
