### ISSUE TITLE
Ssh not avalible in latest version

### ISSUE THREAD

**Issue by theczarek** [felddy/foundryvtt-docker#281]
# 🐛 Bug Report #

After deploing new Foundry V9 instalation  on hosting service (using Unicloud.pl) using docker I cannot connect via ssh. 
Version lower than 9 working fine on the same configuration. Cannot connect niteher via Fillezilla with keys nor via native webssh console on hosting service panel.

**Comment by felddy** [comment]
I'm sorry I cannot provide any help with this issue as this container does not implement an `ssh` server.  

If you could elaborate more, and use the issue template, I might be able to point you in the right direction.

**Comment by michalzc** [comment]
@theczarek  I had the same problem and after some digging, I nailed it down. Looks like the unicloud.pl has a problem with newer versions of the alpine system. Check out the code, update the Dockerfile as below and build your own image. 
-ARG NODE_IMAGE_VERSION=16-alpine3.15
+ARG NODE_IMAGE_VERSION=16-alpine3.11
