### ISSUE TITLE
Support parsing FOUNDRY_VERSION with `release` tag as well as null/empty FOUNDRY_VERSION

### ISSUE THREAD

**Issue by TaakoMagnusen** [felddy/foundryvtt-docker#299]
# 🚀 Feature Proposal #

I'm using unraid to set up the docker and it supports optional variables but requires a default, meaning I have to either remove the foundry version variable or set it to a valid default. I'd like to be able to use the `release` docker image but pull an image based on FOUNDRY_VERSION, where null/empty FOUNDRY_VERSION (but still defined) pulls the latest foundry.

Also it would be awesome if it could parse the variable similar to the way tags work, so `9` pulls the latest 9.xxx.x version, and 9.255 pulls the latest 9.255.x version.

## Motivation ##

This will make the FOUNDRY_VERSION variable more robust and make it friendly to Unraid docker templates.

## Example ##

using `foundryvtt:release` I set FOUNDRY_VERSION but do not specify it (so it's blank/empty string/null), this pulls the most recent stable foundry version

using `foundryvtt:release` I set FOUNDRY_VERSION to 9 this pulls the most recent stable 9.xxx foundry version

## Pitch ##

This would make it so user's can use the environmental variable to update their foundry version.

**Comment by felddy** [comment]
The `FOUNDRY_VERSION` variable is used internally by the container and should be modified during normal uses.  

It is set in the `Dockerfile` to the version that has been tested and supported by the container's image:
https://github.com/felddy/foundryvtt-docker/blob/80bc7cc1ccf9a9e407ca1e7c7d1f6fb2d67a2cc1/Dockerfile#L4

I'm not sure what unraid is doing, but I suspect it is similar to the behavior of Portainer that is causing its users the same trouble and confusion.  

See:
- https://github.com/felddy/foundryvtt-docker/discussions/208
- https://github.com/felddy/foundryvtt-docker/discussions/291
