### ISSUE TITLE
Persistent/bindable install dir for foundry app

### ISSUE THREAD

**Issue by ErroneousBosch** [felddy/foundryvtt-docker#304]
# 🚀 Feature Proposal #

A clear and concise description of what the feature is.

Allow the 'resources' directory, where foundryvtt is installed, to be bindable. 

Please outline the motivation for the proposal.

Downloads from foundryvtt.com can be painfully slow these days and that 184mb package can take 20+minutes, and with such a large package, it would be nice to be able to have the foundryvtt software package on something that persists, like a volume bind. In a k8s environment, with the way pods work, this can lead to 25 min + startup times., similarly if you are recreating the container to change settings in a normal container environment.

Please provide an example for how this feature would be used.

It looks like there is a version check built into the entrypoint.sh already, so the install can still happen if needed. Rather than doing an `rm -r resources`, switching this to `rm -r resources/*` might do the trick.

Why does this feature belong in this project?

Is a deployment issue not a foundry issue.

**Comment by felddy** [comment]
Take a look at the `CONTAINER_CACHE` environment variable.  I think this might be what you're looking for as far as speeding up distribution downloads:

https://github.com/felddy/foundryvtt-docker#pre-cached-distribution-variable

Let me know if this addresses your concern.

**Comment by ErroneousBosch** [comment]
I think this will cover it. Thank you
