### ISSUE TITLE
Investigate excessive download loop of FoundryVTT releases from S3

### ISSUE THREAD

**Issue by felddy** [felddy/foundryvtt-docker#306]
# 🐛 Bug Report #

There is a report of what seem to be misconfigured containers constantly downloading Foundry VTT releases on a loop.  

## Facts ##

- This behavior started on `2022-03-14` and is still continuing. 
- A single IP transferred over 30GB of data in a 30 minute period.
- Version `9.249` and `9.255` are the most downloaded release versions.

## Timeline ##

- 2022-02-01 19:25 EST - [Container release `9.249.0`](https://github.com/felddy/foundryvtt-docker/releases/tag/v9.249.0)
- 2022-03-01 20:25 EST - [Container release `9.251.0`](https://github.com/felddy/foundryvtt-docker/releases/tag/v9.251.0)
- 2022-03-04 23:15 EST - [Container release `9.254.0`](https://github.com/felddy/foundryvtt-docker/releases/tag/v9.254.0)
- 2022-03-05 19:39 EST - [Container release `9.255.0`](https://github.com/felddy/foundryvtt-docker/releases/tag/v9.255.0)
- 2022-03-14 00:00 EST - FoundryVTT S3 traffic doubles
- 2022-03-23 18:03 EDT - [Container release `10.260.0`](https://github.com/felddy/foundryvtt-docker/releases/tag/v10.260.0)

### Timeline takeaway ###

No remarkable changes were made to the codebase around the time this behavior started.  The most recent release was two weeks before the behavior started.   A comprehensive list of all code changes from `9.249` to `9.255` can be reviewed here: https://github.com/felddy/foundryvtt-docker/compare/v9.249.0...v9.255.0

## Container pull count ##

Docker Hub [does not provide a detailed history](https://github.com/docker/hub-feedback/issues/1047) of image downloads.  We can query for the current number of pulls.  A Docker Hub manifest pull isn't necessarily a download of the layers of an image, but a request to see if the image has changed.  

`curl -s https://hub.docker.com/v2/repositories/felddy/foundryvtt/ | jq -r ".pull_count,.last_updated"`

```console
24566393
2022-04-02T18:36:22.533609Z

24566506
2022-04-02T18:36:22.533609Z

24567286
2022-04-03T10:17:03.651663Z

24568599
2022-04-04T10:30:27.103553Z

24569666
2022-04-05T02:20:33.220130Z

24570465
2022-04-05T10:30:32.720369Z

24575613
2022-04-08T10:25:09.481336Z

24594090
2022-04-25T13:44:45.014965Z
```

## Container curl user-agents ##

I've captured the user agents for each of the containers released the time period of interest in hopes it could help with the investigation.  Short version: they're all `curl/7.80.0`

- 9.249.0: `curl/7.80.0`
- 9.251.0: `curl/7.80.0`
- 9.254.0: `curl/7.80.0`
- 9.255.0: `curl/7.80.0`
- 10.260.0: `curl/7.80.0`

## Verify S3 is still honoring `If-Modified-Since` header ##

I've verified that S3 is still correctly honoring the [`If-Modified-Since`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Modified-Since) that the container uses to prevent re-downloads of the FoundryVTT releases.   It is correctly behaving and returning a `304 Not Modified` instead of a `200`. 

Output from the `curl` command used by the container:
https://github.com/felddy/foundryvtt-docker/blob/87d767a7834c296db73ca0c100c5a80cea7b47ce/src/entrypoint.sh#L124-L125
```console
...
> GET /releases/9.255/FoundryVTT-9.255.zip?AWSAccessKeyId=xxx&Signature=xxx&Expires=1648960102 HTTP/1.1
> Host: foundryvtt.s3.amazonaws.com
> User-Agent: curl/7.80.0
> Accept: */*
> If-Modified-Since: Sun, 03 Apr 2022 04:24:52 GMT
> 
{ [5 bytes data]
* Mark bundle as not supporting multiuse
< HTTP/1.1 304 Not Modified
< x-amz-id-2: RqnohuxdCuEEdfuiJV9k0ANZYfgz9LN9OsGPQy8ZxN9TkicrPwQD0/mosbjlvWKxhs9OHyLlflI=
< x-amz-request-id: 44J06MTKR5HXSJDC
< Date: Sun, 03 Apr 2022 04:25:49 GMT
< Last-Modified: Sat, 05 Mar 2022 22:28:23 GMT
...
```

### Scenario 1 ###

This is the most likely scenario.  

- A container is configured with an aggressive [restart policy](https://docs.docker.com/compose/compose-file/compose-file-v3/#restart_policy) 
- [`CONTAINER_CACHE` ](https://github.com/felddy/foundryvtt-docker#pre-cached-distribution-variable) is not configured
- The container [`entrypoint.sh`](https://github.com/felddy/foundryvtt-docker/blob/develop/src/entrypoint.sh) completes without error, but a failure occurs later causing the [`launcher.sh`](https://github.com/felddy/foundryvtt-docker/blob/develop/src/launcher.sh) or [NodeJS child processes](https://github.com/felddy/foundryvtt-docker/blob/87d767a7834c296db73ca0c100c5a80cea7b47ce/src/launcher.sh#L61-L63) to exit. 
- Someone fired this up and left it running.  (see outstanding question about number of IPs doing this)

I'm not sure how to specifically create this scenario today, but [from past experience there have been ways to cause crashes](https://github.com/felddy/foundryvtt-docker/issues?q=is%3Aissue+crash+).  (users will always find a way)

### Scenario 2 ###

TBD...

## Possible mitigations / improvements ##

1. Make `CONTAINER_CACHE` default to `/data/container_cache`.  The would cause containers to cache their downloads by default.  This is a pretty significant behavior change, but I would hope this is how most users are using it anyway. 
1. Add logic that if `CONTAINER_CACHE` is disabled the entry point will handle child exits with a logged error instead of allowing the container to exit, and possibly restart in a loop.  
1. Annotate the `curl` and `node` [user-agent headers with a comment](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent) that identifies the container making the request.  e.g.; `curl/7.80.0  (felddy/foundryvtt:9.255.0)`. This probably won't have a large impact in the short term, but will provide more information if things like this continue to occur in the future.
 1. Change example `docker-compose.yml` documentation to use `restart: "no"` instead of `restart: "unless-stopped"`. This is currently the case in the example `docker-compose.yml` file in the repo, but not in the README.  

## Outstanding questions ##
- [ ] Is the user agent for misbehaving clients uniformly `curl/7.80.0`?
- [ ] Approximately how many IPs are exhibiting this behavior?
  - [ ] Is this a couple of misconfigured systems, or something in the container?
- [ ]  Does this loop include reauthenticating to foundryvtt.com and generating a new [pre-signed URL](https://docs.aws.amazon.com/AmazonS3/latest/userguide/ShareObjectPreSignedURL.html)?

**Comment by felddy** [comment]
Two releases were made that will hopefully reduce the network load and provide additional transparancy in the future:
- https://github.com/felddy/foundryvtt-docker/releases/tag/v9.255.1
- https://github.com/felddy/foundryvtt-docker/releases/tag/v10.260.1

I'm going to leave this issue open for now.

**Comment by firstchrono** [comment]
@felddy what's the timeline or ETA to get this change into the 'latest' tag on the container?

**Comment by felddy** [comment]
> @felddy what's the timeline or ETA to get this change into the 'latest' tag on the container?

@firstchrono the changes from PR #307 were released 12 days ago.   See my previous comments above for more details about the releases.  Both `:release` and `:prerelease` tags now include these changes.  Also `:latest` since [`:latest` == `:release`](https://github.com/felddy/foundryvtt-docker#image-tags)

I'm leaving this issue open for now until the evaluation of the changes can be determined.  

Please let me know if you have any other questions.

**Comment by felddy** [comment]
After talking with the Foundry devs it seems this (along with several actions on their side) has mitigated this issue for now.

If there are reports of this resurfacing I will reopen it.
