### ISSUE TITLE
Enable custom CA for node-fetch

### ISSUE THREAD

**Issue by krb1997** [felddy/foundryvtt-docker#317]
# 🚀 Feature Proposal #

Foundry uses Node-Fetch for downloading modules and systems. Node uses its own CA store for verifying the remote but for those of use who use our own SCM servers, which use self signed CA's, we get errors.
Node has an environment variable which allows additional CA's to be included: `NODE_EXTRA_CA_CERTS`.
The additional code is minimal in `src/launcher.sh`:
``` bash
env -i HOME="$HOME" NODE_EXTRA_CA_CERTS="$NODE_EXTRA_CA_CERTS" node "$@" || log_error "Node process exited with code $?"
```

This would expose `NODE_EXTRA_CA_CERTS` allowing users to mount and add additional CA's through the docker-compose file. 

I'm happy to put a PR in for the change + docs, just wanted to get your thoughts first in case you would prefer a custom variable like: `FOUNDRY_ADDITIONAL_CA_BUNDLE`

**Comment by felddy** [comment]
I think this is a great idea.  

I was looking through the list of [Node.js environment variables](https://nodejs.org/docs/latest-v16.x/api/cli.html#environment-variables) to see what was available.  I think exposing `NODE_OPTIONS`, and `NODE_DEBUG` could also be useful.   

It might even make sense to allow all `NODE_*`.  Using `env -S` and a regex with some `sed` fu.

**Comment by krb1997** [comment]
Looks like the BusyBox implementation of `env` doesn't support `-S`. I put together a PR with an alternative approach. It features a "Whitelist" so this can be expanded upon in the future if need be.

**Comment by felddy** [comment]
@krb1997 your contributions have been merged and are currently being built by the continuous integration.  

When you get a chance can you please pull `felddy/foundryvtt:edge` (or `felddy/foundryvtt:sha-291b3d31 `) and test that everything is working for you.  

If it all looks good please feel free to close this issue.  

Thank you again for a great contribution.  This is actually super useful for my own testing using `NODE_DEBUG=http,net`.  

Cheers!

**Comment by krb1997** [comment]
Tested and working. I can now provide my CA bundle with `NODE_EXTRA_CA_CERTS` and FoundryVTT verifies the domain ok. 
Thanks for the help and your continued work on this!
