### ISSUE TITLE
Silent v9.269 is out...

### ISSUE THREAD

**Issue by bsas** [felddy/foundryvtt-docker#326]
Looks like there is a v9.269 with minor bug fixes out...

**Comment by felddy** [comment]
Lol.  Stealth release! 🤣 

- https://foundryvtt.com/releases/9.269 
- https://discord.com/channels/170995199584108546/675738274572271656/966085743715958785

I'll start a build testing, and release it ASAP. 

@bsas Thanks for the nudge!

**Comment by felddy** [comment]
@bsas The [`9.269` release](https://github.com/felddy/foundryvtt-docker/releases/tag/v9.269.0) is [building](https://github.com/felddy/foundryvtt-docker/actions/runs/2204399430) and should be in the Docker repositories in about 10 minutes.  

Thanks again for the ping.
