### ISSUE TITLE
Starting without a License

### ISSUE THREAD

**Issue by ZeroEnna** [felddy/foundryvtt-docker#329]
# 🚀 Feature Proposal #

For commercial use of this image, it would be a good idea to start with a "blank" system, e.g. no license key.
The reason for this is that it's the easiest way to start. Customers would then have to buy their license key first and enter it after ordering hosted services. We don't have to save their Foundry-Account data in our database, thus ensuring data protection by deniability

## Motivation ##

We are currently planning a hosting service for the european market.

## Pitch ##

It would help making hosting easier and more accessible.

**Comment by felddy** [comment]
I'm not sure exactly what the requirements are for your feature.  Could you please elaborate?  

This container already does "start with a 'blank' system".  In fact, it is so "blank" that there is no FoundryVTT installed.  This is why the credentials or distribution URL are required.  

I suspect that you are asking for an image that has FoundryVTT pre-installed, but unlicensed.  

Be advised that the [Foundry VTT License](https://foundryvtt.com/article/license/) limits how the software can be distributed.

That said, the ability to pre-install Foundry VTT is already supported by this project, but pre-installed images are not published.

See: 
- https://github.com/felddy/foundryvtt-docker#pre-installed-distribution-builds
- `FOUNDRY_LICENSE_KEY`: https://github.com/felddy/foundryvtt-docker#optional-variables

Let me know if this is what you are looking for, or if you can clarify your feature proposal.
