### ISSUE TITLE
Keep existing user's permissions on /data/Data

### ISSUE THREAD

**Issue by boideltier** [felddy/foundryvtt-docker#340]
# 🚀 Feature Proposal #

As of right now, the ownership of the `/data` directory is changed to match the server's at startup. This overrides the ownership of existing users, who might have write permissions on the directory. Using the enviroment variable `CONTAINER_PRESERVE_OWNER`, this can be prevented, but raises issues on its own. When preserving the ownership of a directory in `/data/Data/` for example, it's impossible to launch an existing world as Foundry lacks access to the `worlds` directory and files within. Preserving the ownership of multiple directories in `/data/Data/`, for example with `CONTAINER_PRESERVE_OWNER=/data/Data/maps\|/data/Data/tokens` disables the file upload via Foundry's GUI in these directories.

Ideally, there'd be an option to **keep the existing permissions on the directory for already existing users, but also give neccessary permissions to the container** in order to be able to upload files via the Foundry GUI. This would've been the expected behaviour.

## Motivation  & Example

This would make content management easier in many cases. Depending on the task, different methods might be easier. Uploading entire scores of soundtracks and sorting them into directories is easier done via SMB share or FTP. But if a player wants to upload a new icon for their character, the GUI would be the preferred method.

**Comment by damccull** [comment]
This is likely solved by adding or using the ability to change the user launching the server. For instance, making foundry launch as user 1000 within the container by default, and then allowing the UID to be configured via an environment variable. Right now it seems to launch as UID 421 for me. By making it 1000, it'd match the first-created user's ID in the linux system, and for MOST users this would make it work properly by default.

**Comment by damccull** [comment]
Turns out this is already supported. Launch the container with `-e FOUNDRY_GID=1000` and `-e FOUNDRY-UID=1000` or put those in the docker-compose under environment variables.

I imagine 421 was chosen so as to not easily coincide with someone else's UID/GID and accidentally grant bad permissions in multi-user environments.
