### ISSUE TITLE
CONTAINER_PRESERVE_OWNER and groups

### ISSUE THREAD

**Issue by benbarbour** [felddy/foundryvtt-docker#350]
# 🐛 Bug Report #

I can't seem to get `CONTAINER_PRESERVE_OWNER` working, or perhaps it doesn't work on groups?

What seems to work for me is to let the container change the owner of the entire `/data` folder, but then I run `chown -R :<myGroup> ~/foundry_data/Data/assets`. Then both my user and the container's have access to `assets` folder. However, every time the container restarts I have to re-run that command because it sets the group back to the container's, despite this config:

```iml
services:
  foundry:
    environment:
      - CONTAINER_PRESERVE_OWNER=/data/Data/assets
```

Here's the requested container info:

```console
❯ docker inspect --format='{{range $k, $v := .Config.Labels}}
    {{- printf "%s = \"%s\"\n" $k $v -}} {{end}}' \
    felddy/foundryvtt:release
com.foundryvtt.version = "9.269"
org.opencontainers.image.authors = "markf+github@geekpad.com"
org.opencontainers.image.created = "2022-04-21T21:19:49Z"
org.opencontainers.image.description = "An easy-to-deploy Dockerized Foundry Virtual Tabletop server."
org.opencontainers.image.licenses = "MIT"
org.opencontainers.image.revision = "fccd7b757f98eaa97d8f29f7da53efb7d4971c9c"
org.opencontainers.image.source = "https://github.com/felddy/foundryvtt-docker.git"
org.opencontainers.image.title = "foundryvtt-docker"
org.opencontainers.image.url = "https://github.com/felddy/foundryvtt-docker"
org.opencontainers.image.vendor = "Geekpad"
org.opencontainers.image.version = "9.269.0"
```

**Comment by felddy** [comment]
I'm unable to reproduce this.  

I have `CONTAINER_PRESERVE_OWNER=/data/Data/assets\|/data/Data/more-assets` in my test config and I can see that neither path `gid` or `uid` is modified when I start the container: (I set them to `502:502`)

```console
❱ ls -l data/Data/
total 0
drwxr-xr-x@  4 502    502    128 Jan 23  2021 assets/
drwxr-xr-x@ 23 markf  staff  736 May 25 14:43 modules/
drwxr-xr-x   2 502    502     64 Apr 11  2021 more-assets/
drwxr-xr-x@  4 markf  staff  128 May 25 14:33 systems/
drwxr-xr-x@  8 markf  staff  256 Dec 20 22:56 worlds/
```

The code that implements this: https://github.com/felddy/foundryvtt-docker/blob/dbbf67d6cf8d09fe639b2e2e38a1f758435e7f77/src/entrypoint.sh#L247-L250

I'd be curious if you can figure out why this is failing on your system.  Besides double-checking your configs, or employing the the `FOUNDRY_UID` and `FOUNDRY_GID` as a work-around, I can't offer anything else.  

Feel free to re-open or comment on this issue if you discover anything else.  Good luck.

**Comment by felddy** [comment]
If you haven't already, take a look through the related discussions on the repo: 
- https://github.com/felddy/foundryvtt-docker/discussions?discussions_q=CONTAINER_PRESERVE_OWNER
