### ISSUE TITLE
Support of prerelease 10.276

### ISSUE THREAD

**Issue by DerJJ** [felddy/foundryvtt-docker#391]
Hi, there is already a 10.276 prerelease version out, could you please integrate that?

https://foundryvtt.com/releases/10.276

Thanks

**Comment by felddy** [comment]
I'll try to get this out today.  There is a new configuration to support in `options.json` so this is a bit more than a normal version bump.  

As a work-around, if you need to test before the new image is published you can manually set the `FOUNDRY_VERSION` environment variable to `10.276`.

**Comment by felddy** [comment]
New `protocol` option in `options.json`

See:
- https://github.com/foundryvtt/foundryvtt/issues/6506

Note that `protocol` is not yet defined in the official `options.json` documentation:
- https://foundryvtt.com/article/configuration/#application-configuration
- https://github.com/foundryvtt/foundryvtt/blob/master/articles/configuration.html

**Comment by felddy** [comment]
See:
- https://github.com/felddy/foundryvtt-docker/releases/tag/v10.276.0
