### ISSUE TITLE
CONTAINER_PATCHES parameter not set error.

### ISSUE THREAD

**Issue by TimPansino** [felddy/foundryvtt-docker#44]
# 🐛 Bug Report

Error appears in logs related to unset CONTAINER_PATCHES variable when this is supposed to be optional. Does not prevent startup.

## To Reproduce

- Start a container without the CONTAINER_PATCHES env var set.
- Observe error in log stream.

## Expected behavior

No errors logged for unused parameters.

## Any helpful log output

Please run this command:

```bash
docker inspect --format='{{range $k, $v := .Config.Labels}}
    {{- printf "%s = \"%s\"\n" $k $v -}} {{end}}' \
    felddy/foundryvtt:latest
```

Paste the results here:

```console
com.foundryvtt.version = "0.6.4"
org.opencontainers.image.authors = "markf+github@geekpad.com"
org.opencontainers.image.created = "2020-06-29 19:55:59+00:00"
org.opencontainers.image.licenses = "CC0-1.0"
org.opencontainers.image.revision = "61dd6a9b3a2394716bb7ac367f07f5e953f689c3"
org.opencontainers.image.source = "https://github.com/felddy/foundryvtt-docker"
org.opencontainers.image.title = "Foundry Virtual Tabletop"
org.opencontainers.image.vendor = "Geekpad"
org.opencontainers.image.version = "0.6.4"
```

Run the container with `CONTAINER_VERBOSE` set to `true`,and paste any useful
log output here:

```console
foundry    | ./entrypoint.sh: line 107: CONTAINER_PATCHES: parameter not set
```

**Comment by TimPansino** [comment]
https://github.com/felddy/foundryvtt-docker/blob/61dd6a9b3a2394716bb7ac367f07f5e953f689c3/src/entrypoint.sh#L107

Recommendation:

```
if [[ -n ${CONTAINER_PATCHES:-}" ]]; then
```

**Comment by felddy** [comment]
The problem is this line: 
https://github.com/felddy/foundryvtt-docker/blob/61dd6a9b3a2394716bb7ac367f07f5e953f689c3/src/entrypoint.sh#L98

I forgot to move it down below the new `CONTAINER_PATCHES` section. 

But more importantly the automated testing was happy with this failure.   The "Ready" text the tests are looking for was found earlier in the log, and was no longer a valid indicator of the system starting.  

Good catch!

**Comment by felddy** [comment]
Undoing auto-close so @TimPansino can verify.

**Comment by felddy** [comment]
A new release is being built and tested.  It should be out in a few minutes:
https://github.com/felddy/foundryvtt-docker/runs/823965856?check_suite_focus=true

Thanks again for catching this.  Please let me know if this fix also works for you.

**Comment by TimPansino** [comment]
Everything looks good on my end. 👍

**Comment by felddy** [comment]
Sweet!  Thanks!
