### ISSUE TITLE
Cannot look in with bash

### ISSUE THREAD

**Issue by OriginLive** [felddy/foundryvtt-docker#516]
### Bug description

Can we get bash shell, so I can browse the files. I need to update some of the local foundry files, but bash fails to open on the container.

### Steps to reproduce

Open docker terminal.
<img width="508" alt="image" src="https://user-images.githubusercontent.com/24319526/201505674-3b4090f0-6659-42cf-9e8a-e282e9ad85e2.png">
see this

### Expected behavior

i would like to copy files and edit files inside

### Container metadata

```shell
latest release
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felddy** [comment]
You can open a shell at `/bin/sh`.  This is the busybox shell based on `dash`.

```console
docker run --rm -it --entrypoint /bin/sh felddy/foundryvtt:release
/home/foundry # sh --help
BusyBox v1.34.1 (2022-07-19 20:11:24 UTC) multi-call binary.

Usage: sh [-il] [-|+Cabefmnuvx] [-|+o OPT]... [-c 'SCRIPT' [ARG0 ARGS] | FILE [ARGS] | -s [ARGS]]

Unix shell interpreter
```

I hope this helps.
