### ISSUE TITLE
Problem running in IPv6-only environment

### ISSUE THREAD

**Issue by wasabipesto** [felddy/foundryvtt-docker#531]
### Bug description

I am attempting to run foundryvtt-docker on a server that does not have an IPv4 address, so all external connections on this machine have to connect to IPv6 addresses. Most services are able to fall back to AAAA records when typical A records fail, but the current release version of foundryvtt-docker does not fall back to IPv6 at all. 

Reading online, it looks like this is a problem with earlier versions of node. After building the container with `NODE_IMAGE_VERSION=19-alpine3.15` the issue is resolved, but I imagine there is a lower minimum version that would also work.

As a note, `foundryvtt.com` does not have an IPv6 address, I am using nat64.net to provide IPv6 addresses for such sites that do not have IPv6 set up yet. This service has been working for every other application on my network, though I am happy to try a different one if it would be helpful for troubleshooting.

### Steps to reproduce

Running the latest version, the authenticate action fails because it only uses an IPv4 address:

```
justin@kalak:/opt$ docker run -it --env FOUNDRY_USERNAME='<username>' --env FOUNDRY_PASSWORD='<password>' --env CONATINER_VERBOSE=True --publish 30000:30000/tcp felddy/foundryvtt:sha-f24b4a0
Entrypoint | 2022-12-03 14:39:58 | [info] Starting felddy/foundryvtt container v10.291.0
Entrypoint | 2022-12-03 14:39:58 | [info] No Foundry Virtual Tabletop installation detected.
Entrypoint | 2022-12-03 14:39:58 | [info] Using FOUNDRY_USERNAME and FOUNDRY_PASSWORD to authenticate.
Authenticate | 2022-12-03 14:39:58 | [info] Requesting CSRF tokens from https://foundryvtt.com
Authenticate | 2022-12-03 14:39:58 | [error] Unable to authenticate: request to https://foundryvtt.com/ failed, reason: connect ENETUNREACH 18.237.161.213:443
```

Entering the container, we can get the correct AAAA address from dig and even connect to `foundryvtt.com` with curl. This proves that the container is set up correctly, there is something in the node application that is not handling IPv6 correctly.

```
justin@kalak:/opt$ docker run -it --env FOUNDRY_USERNAME='<username>' --env FOUNDRY_PASSWORD='<password>' --env CONATINER_VERBOSE=True --publish 30000:30000/tcp --entrypoint /bin/sh felddy/foundryvtt:sha-f24b4a0 
/home/foundry # apk add --update bind-tools -q
/home/foundry # dig +short foundryvtt.com AAAA
2a00:1098:2b::1:12ed:a1d5
2a01:4f8:c2c:123f:64:5:12ed:a1d5
2a00:1098:2c::5:12ed:a1d5
/home/foundry # curl foundryvtt.com
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.22.0</center>
</body>
</html>
/home/foundry #
```

When we set the Dockerfile variable `ARG NODE_IMAGE_VERSION=19-alpine3.15` (up from 16), the image builds and authenticates successfully. (Note: I was unable to even build the image with node 16 on my machine due to failing on `RUN npm install && npm install --global typescript`)

```
Entrypoint | 2022-12-03 09:29:35 | [debug] Timezone set to: America/New_York
Entrypoint | 2022-12-03 09:29:35 | [info] Starting felddy/foundryvtt container v
Entrypoint | 2022-12-03 09:29:35 | [debug] CONTAINER_VERBOSE set.  Debug logging enabled.
Entrypoint | 2022-12-03 09:29:35 | [info] No Foundry Virtual Tabletop installation detected.
Entrypoint | 2022-12-03 09:29:35 | [info] Using FOUNDRY_USERNAME and FOUNDRY_PASSWORD to authenticate.
Authenticate | 2022-12-03 09:29:35 | [debug] Saving cookies to: cookiejar.json
Authenticate | 2022-12-03 09:29:35 | [info] Requesting CSRF tokens from https://foundryvtt.com
Authenticate | 2022-12-03 09:29:35 | [debug] Fetching: https://foundryvtt.com
Authenticate | 2022-12-03 09:29:36 | [info] Logging in as: <username>
Authenticate | 2022-12-03 09:29:36 | [debug] Fetching: https://foundryvtt.com/auth/login/
Authenticate | 2022-12-03 09:29:38 | [debug] Community URL: /community/wasabipesto
Authenticate | 2022-12-03 09:29:38 | [info] Successfully logged in as: wasabipesto
Entrypoint | 2022-12-03 09:29:38 | [info] Using authenticated credentials to download release.
...
```

I imagine there is probably a reason why node is still on version 16, and I don't want to just submit a pull request bumping the version without knowledge of what it would affect. However, the current version is causing problems for the increasing number of users without IPv4 addresses.

### Expected behavior

I expect the application to fall back from IPv4 to IPv6 when the IPv4 address is unreachable.

### Container metadata

```shell
com.foundryvtt.version = "10.291"
org.opencontainers.image.authors = "markf+github@geekpad.com"
org.opencontainers.image.created = "2022-12-03T10:06:14.622Z"
org.opencontainers.image.description = "An easy-to-deploy Dockerized Foundry Virtual Tabletop server."
org.opencontainers.image.licenses = "MIT"
org.opencontainers.image.revision = "f24b4a0107ae397260300ac25ca7687e55616919"
org.opencontainers.image.source = "https://github.com/felddy/foundryvtt-docker"
org.opencontainers.image.title = "foundryvtt-docker"
org.opencontainers.image.url = "https://github.com/felddy/foundryvtt-docker"
org.opencontainers.image.vendor = "Geekpad"
org.opencontainers.image.version = "10.291.0"

(note this is from the sha-f24b4a0 image, I also tried with release)
```

### Relevant log output

```console
Entrypoint | 2022-12-03 14:39:58 | [info] Starting felddy/foundryvtt container v10.291.0
Entrypoint | 2022-12-03 14:39:58 | [info] No Foundry Virtual Tabletop installation detected.
Entrypoint | 2022-12-03 14:39:58 | [info] Using FOUNDRY_USERNAME and FOUNDRY_PASSWORD to authenticate.
Authenticate | 2022-12-03 14:39:58 | [info] Requesting CSRF tokens from https://foundryvtt.com
Authenticate | 2022-12-03 14:39:58 | [error] Unable to authenticate: request to https://foundryvtt.com/ failed, reason: connect ENETUNREACH 18.237.161.213:443

(from above)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felddy** [comment]
Thanks for reporting this.  I'm a huge proponent of IPv6.  We're going to get this fixed.  I've got to do a bit of research first to see if Foundry is still having issues with node 18.  They are still recommending 14 in their installation guide, and messages on Discord from July claim 18 was not supported.   

Let me see if I can get a response from the devs about using 18.  My guess is that it issues have been ironed out.

See:
 - https://nodejs.dev/en/about/releases/
 - https://github.com/foundryvtt/foundryvtt/blob/master/articles/installation.html
 - https://discord.com/channels/170995199584108546/486930822465716249/1002950173590306926

**Comment by felddy** [comment]
While we wait for a response from the FoundryVTT devs I've created a [branch](https://github.com/felddy/foundryvtt-docker/tree/node-18) that is building a node `18` image of the container. 

When you get a chance could you please pull `felddy/foundryvtt:node-18` and let me know  how it behaves for you?

**Comment by wasabipesto** [comment]
The `felddy/foundryvtt:node-18` branch works perfectly! I've logged in and everything seems to be running great. I did a few quick tests and I haven't seen anything weird, but I'll update here if I do.

**Comment by felddy** [comment]
I'm glad this is working for you.  I'm going to keep this issue open until we get a resolution from the FoundryVTT devs.  Then I can merge this change into the main branch for the next release.

**Comment by felddy** [comment]
FYSA... The [`v11.299.0` stable release](https://github.com/felddy/foundryvtt-docker/releases/tag/v11.299.0) is now using node 18.

**Comment by daegalus** [comment]
So, I seem to have hit this issue today. I am moving Foundry from a raspberry pi at home to a Hetzner vm. I have IPv6 only in Hetzner for that vm. For my case, the docker image can't hit foundryvtt.com either. So might honestly be a docker issue. I'll test to see if enabling ipv6 in docker helps.

```
Entrypoint | 2023-07-07 21:43:21 | [info] Starting felddy/foundryvtt container v11.305.0
Entrypoint | 2023-07-07 21:43:21 | [info] No Foundry Virtual Tabletop installation detected.
Entrypoint | 2023-07-07 21:43:21 | [info] Using FOUNDRY_USERNAME and FOUNDRY_PASSWORD to authenticate.
Authenticate | 2023-07-07 21:43:22 | [info] Requesting CSRF tokens from https://foundryvtt.com
Authenticate | 2023-07-07 21:45:34 | [error] Unable to authenticate: request to https://foundryvtt.com/ failed, reason: connect ETIMEDOUT 18.237.161.213:443
```

Running the latest release with node 18. There might be more steps that are needed.

**Comment by daegalus** [comment]
Enabling IPv6 for Docker fixed ipv6 in the container, but looks like `foundryvtt.com` no longer has a AAAA record https://www.nslookup.io/domains/foundryvtt.com/dns-records/

[Edit] Some findings. You can use Timed URLs if you modify the host to the `dualstack` url for S3. so `foundryvtt.s3.amazonaws.com` needs to change to `foundryvtt.s3.dualstack.us-west-2.amazonaws.com` for it to work from IPv6.

But the License servers also don't have IPv6 so you still cant use FoundryVTT because it can't validate the license.

**Comment by felddy** [comment]
So I think the original issue has been rectified, but we've morphed into a new issue about FoundryVTT's internet services no longer publishing `AAAA` records.   I'm going to close this issue as fixed. 

I've started a discussion to track the progress of the missing IPv6 FoundryVTT records:
- #752
