### ISSUE TITLE
Reading from secrets fails after pivot to unprivileged user

### ISSUE THREAD

**Issue by pdf** [felddy/foundryvtt-docker#56]
# 🐛 Bug Report

When the `entrypoint.sh` drops privileges via `su-exec`, and calls itself, it loses the ability to read from `/run/secrets/config.json` which is mode 0600 and owned by root:root. This causes a failure of the unprivileged user to read the secrets file, resulting in unpopulated variables, and unconfigured options (eg - admin access key).

## To Reproduce

- Follow instructions from README on setting up docker-compose with secrets
- Attempt to start the container with `docker-compose up`

## Expected behavior

Data from secrets should be correctly populated.

As an aside, I'd strongly suggest splitting the `entrypoint.sh` out into two files - one to do the bootstrapping with elevated privileges, and one that's executed with reduced privs that actually runs the application. This will make it vastly easier to understand what should be done and what privs are expected, at each stage.

I can see a few ways of solving this problem (roughly in order of preference):
- perform all work that needs access to secret data before privileges are dropped
- `export` the variables that hold the associated values, so that the sub-process has access to them without needing access to the secrets file
- modify permissions on the secrets file so that the sub-process can access the file directly

## Any helpful log output

Version info (release tag):
```console
com.foundryvtt.version = "0.6.5"
org.opencontainers.image.authors = "markf+github@geekpad.com"
org.opencontainers.image.created = "2020-07-26 20:39:57+00:00"
org.opencontainers.image.licenses = "MIT"
org.opencontainers.image.revision = "dad0abfe061e9dbae536bf986cd1533a8c2f97e5"
org.opencontainers.image.source = "https://github.com/felddy/foundryvtt-docker"
org.opencontainers.image.title = "Foundry Virtual Tabletop"
org.opencontainers.image.vendor = "Geekpad"
org.opencontainers.image.version = "0.6.5"
```

Log output illustrating problems:
```console
foundry_1  | Entrypoint | 2020-08-02 07:01:24 | [info] Starting felddy/foundryvtt container v0.6.5
foundry_1  | Entrypoint | 2020-08-02 07:01:24 | [info] Reading configured secrets from: /run/secrets/config.json
foundry_1  | Entrypoint | 2020-08-02 07:01:25 | [info] No Foundry Virtual Tabletop installation detected.
foundry_1  | Entrypoint | 2020-08-02 07:01:25 | [info] Using FOUNDRY_USERNAME and FOUNDRY_PASSWORD to authenticate.
foundry_1  | Authenticate | 2020-08-02 07:01:25 | [debug] Saving cookies to: cookiejar.json
foundry_1  | Authenticate | 2020-08-02 07:01:25 | [info] Requesting CSRF tokens from https://foundryvtt.com
foundry_1  | Authenticate | 2020-08-02 07:01:25 | [debug] Fetching: https://foundryvtt.com
foundry_1  | Authenticate | 2020-08-02 07:01:26 | [info] Logging in as: <redacted>
foundry_1  | Authenticate | 2020-08-02 07:01:26 | [debug] Fetching: https://foundryvtt.com/auth/login/
foundry_1  | Authenticate | 2020-08-02 07:01:26 | [debug] Community URL: /community/<redacted>
foundry_1  | Authenticate | 2020-08-02 07:01:26 | [info] Successfully logged in as: <redacted>
foundry_1  | ReleaseURL | 2020-08-02 07:01:26 | [debug] Loading cookies from: cookiejar.json
foundry_1  | ReleaseURL | 2020-08-02 07:01:26 | [info] Fetching S3 pre-signed release URL for 0.6.5...
foundry_1  | ReleaseURL | 2020-08-02 07:01:26 | [debug] Fetching: https://foundryvtt.com/releases/download?version=0.6.5&platform=linux
foundry_1  | ReleaseURL | 2020-08-02 07:01:26 | [debug] S3 presigned URL: https://foundryvtt.s3.amazonaws.com/releases/0.6.5/foundryvtt-0.6.5.zip?<redacted>
foundry_1  | Entrypoint | 2020-08-02 07:01:26 | [info] Using CONTAINER_CACHE: /data/container_cache
foundry_1  | Entrypoint | 2020-08-02 07:01:26 | [info] Downloading Foundry Virtual Tabletop release.
foundry_1  |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
foundry_1  |                                  Dload  Upload   Total   Spent    Left  Speed
foundry_1  |
foundry_1  |   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
foundry_1  |   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
foundry_1  | Entrypoint | 2020-08-02 07:01:27 | [info] Installing Foundry Virtual Tabletop 0.6.5
foundry_1  | Entrypoint | 2020-08-02 07:01:29 | [info] Preserving release archive file in cache.
foundry_1  | Entrypoint | 2020-08-02 07:01:29 | [info] Not modifying existing installation license key.
foundry_1  | Entrypoint | 2020-08-02 07:01:29 | [info] Setting data directory permissions.
foundry_1  | Entrypoint | 2020-08-02 07:01:29 | [info] Switching uid:gid to foundry:foundry and restarting.
foundry_1  | Entrypoint | 2020-08-02 07:01:29 | [info] Starting felddy/foundryvtt container v0.6.5
foundry_1  | Entrypoint | 2020-08-02 07:01:29 | [info] Reading configured secrets from: /run/secrets/config.json
foundry_1  | jq: error: Could not open file /run/secrets/config.json: Permission denied
foundry_1  | jq: error: Could not open file /run/secrets/config.json: Permission denied
foundry_1  | jq: error: Could not open file /run/secrets/config.json: Permission denied
foundry_1  | jq: error: Could not open file /run/secrets/config.json: Permission denied
foundry_1  | Entrypoint | 2020-08-02 07:01:29 | [info] Foundry Virtual Tabletop 0.6.5 is installed.
foundry_1  | Entrypoint | 2020-08-02 07:01:29 | [info] Not modifying existing installation license key.
foundry_1  | Entrypoint | 2020-08-02 07:01:29 | [info] Generating options.json file.
foundry_1  | Entrypoint | 2020-08-02 07:01:29 | [warn] Warning: No 'Admin Access Key' has been configured.
foundry_1  | Entrypoint | 2020-08-02 07:01:29 | [info] Starting Foundry Virtual Tabletop.
foundry_1  | FoundryVTT | 2020-08-02 07:01:30 | [info] Foundry Virtual Tabletop - Version 0.6.5
foundry_1  | FoundryVTT | 2020-08-02 07:01:30 | [info] Running on Node.js - Version 12.18.2
foundry_1  | FoundryVTT | 2020-08-02 07:01:30 | [info] Loading data from user directory - /data
foundry_1  | FoundryVTT | 2020-08-02 07:01:30 | [info] Application Options:
foundry_1  | {
foundry_1  |   "port": 30000,
foundry_1  |   "upnp": false,
foundry_1  |   "fullscreen": false,
foundry_1  |   "hostname": "<redacted>",
foundry_1  |   "routePrefix": null,
foundry_1  |   "sslCert": null,
foundry_1  |   "sslKey": null,
foundry_1  |   "awsConfig": null,
foundry_1  |   "dataPath": "/data",
foundry_1  |   "proxySSL": false,
foundry_1  |   "proxyPort": null,
foundry_1  |   "updateChannel": "release",
foundry_1  |   "noUpdate": true,
foundry_1  |   "world": null,
foundry_1  |   "isElectron": false,
foundry_1  |   "isNode": true,
foundry_1  |   "isSSL": false
foundry_1  | }
foundry_1  | FoundryVTT | 2020-08-02 07:01:31 | [warn] Software license requires signature.
foundry_1  | FoundryVTT | 2020-08-02 07:01:31 | [info] Server started and listening on port 30000
```

**Comment by felddy** [comment]
Thanks for the bug report.  Also thanks for the thoughtful analysis of the issue and possible fixes. 

I'm not able to reproduce it on my development machine or on my production instance.  Both mount up the secrets as `0644`.   That said, it is very clear that this is happening for you, and is a valid issue.   

Mac desktop:
```console
❱ docker --version
Docker version 19.03.8, build afacb8b

❱ docker-compose --version
docker-compose version 1.26.2, build unknown

❱ docker exec -it foundryvtt-docker_foundry_1 stat /run/secrets/config.json
  File: /var/run/secrets/config.json
  Size: 119       	Blocks: 8          IO Block: 4096   regular file
Device: 53h/83d	Inode: 29239031    Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2020-08-02 14:06:02.000000000
Modify: 2020-08-02 14:06:01.000000000
Change: 2020-08-02 14:06:01.000000000
```
Linux (Gentoo) server:
```console
❱ docker --version
Docker version 19.03.8, build afacb8b7f0

❱ docker-compose --version
docker-compose version 1.25.4, build unknown

❱ docker exec -it foundryvtt_foundry_1 stat /var/run/secrets/config.json
  File: /var/run/secrets/config.json
  Size: 119       	Blocks: 8          IO Block: 4096   regular file
Device: 803h/2051d	Inode: 22300966    Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/    node)   Gid: (  100/   users)
Access: 2020-08-02 14:15:00.000000000
Modify: 2020-08-02 14:15:00.000000000
Change: 2020-08-02 14:15:12.000000000
```

According to the most recent [secrets documentation](https://docs.docker.com/compose/compose-file/#long-syntax-2), it looks like the permissions of the mounted files are in flux: 

> The permissions for the file to be mounted in /run/secrets/ in the service’s task containers, in octal notation. For instance, 0444 represents world-readable. The default in Docker 1.13.1 is 0000, but is be 0444 in newer versions. Secrets cannot be writable because they are mounted in a temporary filesystem, so if you set the writable bit, it is ignored.  

Weirdly neither the permissions you are seeing `0600` or mine `0644` are listed.  

Could you provide me with a few details from your environment:
- [ ] version of `docker`.
- [ ] version of `docker-compose`.
- [ ] host operating system and version.

In the meantime I'm going to look at breaking the `entrypoint.sh` up as you recommended.  I cannot recall my original reasoning for restarting the script the way I did. (I'll probably find out.)

Kudos to you for following along!

P.S.  I'm `UTC-4` so I expect this will be a high-latency exchange.  I've been following the news today about the new curfew there.  Stay safe!

**Comment by felddy** [comment]
@pdf I'm testing a possible fix now in branch `bugfix/secret_permissions`.  Could you try building the container locally and testing.    You'll need to temporarily change the tag in your compose file to `felddy/foundryvtt:test`.  

Build command: 
`docker build --build-arg VERSION=0.6.5 --tag felddy/foundryvtt:test https://github.com/felddy/foundryvtt-docker.git#bugfix/secret_permissions`

**Comment by pdf** [comment]
> According to the most recent secrets documentation, it looks like the permissions of the mounted files are in flux

Hmm, unfortunate.

Requested information, docker is installed from the official upstream repos:

```console
$ docker --version
Docker version 19.03.12, build 48a66213fe

$ docker-compose --version
docker-compose version 1.26.2, build eefe0d31

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
```

And for completeness:
```console
$ docker exec -it foundryvtt_foundry_1 stat /run/secrets/config.json 
  File: /run/secrets/config.json
  Size: 261             Blocks: 8          IO Block: 4096   regular file
Device: fc01h/64513d    Inode: 136039      Links: 1
Access: (0600/-rw-------)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2020-08-02 06:35:40.000000000
Modify: 2020-08-02 06:22:18.000000000
Change: 2020-08-02 06:22:18.000000000
```

> P.S. I'm UTC-4 so I expect this will be a high-latency exchange. I've been following the news today about the new curfew there. Stay safe!

Indeed! Thank you very much for your kind sentiments :heart:. I haven't had much time to play with this today unfortunately, but I'll try to get the new branch tested ASAP and report back - I appreciate your attentive response.

**Comment by pdf** [comment]
Happy to report that the `bugfix/secret_permissions` branch appears to resolve this issue here, and I have a fully-functional container running based on that code :tada:

**Comment by felddy** [comment]
Woohoo!  Great success!  🎉  
We'll take the wins where we can find them!  
Thank you again for the great bug report.  I'll create new releases for `0.6.5` and `0.7.0` and push them to Docker hub momentarily.  
Keep safe, and I hope to see you around.  🦘
