### ISSUE TITLE
Server not writing to options.json and CONTAINER_PRESERVE_CONFIG not being respected

### ISSUE THREAD

**Issue by uninvitedguest** [felddy/foundryvtt-docker#581]
### Bug description

I have been attempting to set the Default World in the server configuration and the setting will not stick. Whether it is set in the VTT configuration tab or by editing the options.json file directly, when the container spins up it replaces the options.json file with

`"world": null`

### Steps to reproduce

1. Set environment variable CONTAINER_PRESERVE_CONFIG = TRUE in Portainer/docker-compose.yaml
2. Access the administrative area of Foundry VTT through the web UI. Go to the Configuration tab.
3. The following warning is displayed 
![image](https://user-images.githubusercontent.com/24210277/215379677-334aef3a-03f4-4705-96c0-4c73ce28c5b6.png)
4. Select a default world. Click "Save Configuration.
5. The following prompt is received: 
![image](https://user-images.githubusercontent.com/24210277/215379783-f5875ab3-dd3b-477c-affe-c9a11202e428.png)
6. Click yes and receive the following notice: 
![image](https://user-images.githubusercontent.com/24210277/215379833-f103bd3f-5017-4016-bffd-7f7b38fd1d40.png)
7. Check the contents of options.json - `"world": null` is still present.
8. Stop the container.
9. Edit the options.json to set a default world. Write changes.
10. Start the container.
11. Check the contents of options.json - `"world": null` is again present.

### Expected behavior

I would expect to select a world in the administrative configuration and see it written to options.json, or, edit the options.json and have the data persist when the container starts.

### Container metadata

```shell
com.foundryvtt.version = "10.291"
org.opencontainers.image.authors = "markf+github@geekpad.com"
org.opencontainers.image.created = "2022-12-02T23:36:29.879Z"
org.opencontainers.image.description = "An easy-to-deploy Dockerized Foundry Virtual Tabletop server."
org.opencontainers.image.licenses = "MIT"
org.opencontainers.image.revision = "bf4e42e9570aab7e8de39d7f760cb5f16e19862e"
org.opencontainers.image.source = "https://github.com/felddy/foundryvtt-docker"
org.opencontainers.image.title = "foundryvtt-docker"
org.opencontainers.image.url = "https://github.com/felddy/foundryvtt-docker"
org.opencontainers.image.vendor = "Geekpad"
org.opencontainers.image.version = "10.291.0"
```

### Relevant log output

```console
Entrypoint | 2023-01-30 03:24:36 | [info] Starting felddy/foundryvtt container v10.291.0
Entrypoint | 2023-01-30 03:24:36 | [info] No Foundry Virtual Tabletop installation detected.
Entrypoint | 2023-01-30 03:24:36 | [info] Using FOUNDRY_USERNAME and FOUNDRY_PASSWORD to authenticate.
Authenticate | 2023-01-30 03:24:37 | [info] Requesting CSRF tokens from https://foundryvtt.com
Authenticate | 2023-01-30 03:24:38 | [info] Logging in as: <email@domain.com>
Authenticate | 2023-01-30 03:24:40 | [info] Successfully logged in as: <username>
Entrypoint | 2023-01-30 03:24:40 | [info] Using authenticated credentials to download release.
ReleaseURL | 2023-01-30 03:24:40 | [info] Fetching S3 pre-signed release URL for build 291...
Entrypoint | 2023-01-30 03:24:41 | [info] Using CONTAINER_CACHE: /data/container_cache
Entrypoint | 2023-01-30 03:24:41 | [info] Downloading Foundry Virtual Tabletop release.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Entrypoint | 2023-01-30 03:24:42 | [info] Installing Foundry Virtual Tabletop 10.291
Entrypoint | 2023-01-30 03:24:49 | [info] Preserving release archive file in cache.
Entrypoint | 2023-01-30 03:24:49 | [info] Not modifying existing installation license key.
Entrypoint | 2023-01-30 03:24:49 | [info] Setting data directory permissions.
Entrypoint | 2023-01-30 03:24:50 | [info] Starting launcher with uid:gid as foundry:foundry.
Launcher | 2023-01-30 03:24:50 | [info] Generating options.json file.
Launcher | 2023-01-30 03:24:50 | [info] Setting 'Admin Access Key'.
Launcher | 2023-01-30 03:24:50 | [info] Starting Foundry Virtual Tabletop.
FoundryVTT | 2023-01-30 03:24:54 | [info] Running on Node.js - Version 16.18.1
FoundryVTT | 2023-01-30 03:24:54 | [info] Foundry Virtual Tabletop - Version 10 Build 291
FoundryVTT | 2023-01-30 03:24:54 | [info] User Data Directory - "/data"
FoundryVTT | 2023-01-30 03:24:54 | [info] Application Options:
{
  "awsConfig": null,
  "compressStatic": false,
  "fullscreen": false,
  "hostname": null,
  "language": "en.core",
  "localHostname": null,
  "passwordSalt": null,
  "port": 30000,
  "protocol": null,
  "proxyPort": null,
  "proxySSL": false,
  "routePrefix": null,
  "sslCert": null,
  "sslKey": null,
  "updateChannel": "stable",
  "upnp": false,
  "upnpLeaseDuration": null,
  "world": null,
  "adminPassword": "••••••••••••••••••••••••••••••••",
  "serviceConfig": null
}
FoundryVTT | 2023-01-30 03:24:54 | [info] Software license verification succeeded
FoundryVTT | 2023-01-30 03:24:55 | [info] Server started and listening on port 30000
FoundryVTT | 2023-01-30 03:25:06 | [info] Created client session 52471a42ab00f4f2c4f3b56f
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felddy** [comment]
Thanks for the detailed report.

When the `CONTAINER_PRESERVE_CONFIG ` variable is set to `true` and the `options.json` or `admin.txt` files exist you should see two warning messages in your logs that looks like this:

`[warn] CONTAINER_PRESERVE_CONFIG is set: Not updating options.json`
`[warn] CONTAINER_PRESERVE_CONFIG is set: Not updating admin.txt`

The lack of these messages in your logs means that either the `CONTAINER_PRESERVE_CONFIG` environment variable isn't making it into the environment, or that the `/data` volume that you are storing your configuration files on is not persistent.

I'd verify that the method you are using to set the environment variables is correct.  As a test try setting `CONTAINER_VERBOSE` to `true`.  If it works you'll see the following line right at startup:

`[debug] CONTAINER_VERBOSE set.  Debug logging enabled.`

Let me know if this helps, and anything else you discover.

The logic for these checks can be found in `launcher.sh`:
https://github.com/felddy/foundryvtt-docker/blob/0cf45c50cbf3e3f379cdb9f47c01220177c15331/src/launcher.sh#L29-L48

Here is what the log looks like with the warnings in-line:

```console
Entrypoint | 2023-01-30 09:37:05 | [info] Installing Foundry Virtual Tabletop 10.291
Entrypoint | 2023-01-30 09:37:10 | [debug] Installation completed.
Entrypoint | 2023-01-30 09:37:10 | [info] Preserving release archive file in cache.
Entrypoint | 2023-01-30 09:37:10 | [debug] Patching GUI update and configuration messages.
Entrypoint | 2023-01-30 09:37:10 | [info] Not modifying existing installation license key.
Entrypoint | 2023-01-30 09:37:10 | [info] Setting data directory permissions.
Entrypoint | 2023-01-30 09:37:14 | [debug] Completed setting directory permissions.
Entrypoint | 2023-01-30 09:37:14 | [info] Starting launcher with uid:gid as 501:20.
Launcher | 2023-01-30 09:37:15 | [debug] Ensuring /data/Config directory exists.
Launcher | 2023-01-30 09:37:15 | [warn] CONTAINER_PRESERVE_CONFIG is set: Not updating options.json
Launcher | 2023-01-30 09:37:15 | [warn] CONTAINER_PRESERVE_CONFIG is set: Not updating admin.txt
Launcher | 2023-01-30 09:37:15 | [info] Starting Foundry Virtual Tabletop.
FoundryVTT | 2023-01-30 09:37:18 | [info] Running on Node.js - Version 16.18.1
FoundryVTT | 2023-01-30 09:37:18 | [info] Foundry Virtual Tabletop - Version 10 Build 291
FoundryVTT | 2023-01-30 09:37:18 | [info] User Data Directory - "/data"
```

**Comment by uninvitedguest** [comment]
Problem solved. `CONTAINER_PRESERVE_CONFIG` was set to `TRUE` instead of `true`.

Thank you for your help.

**Comment by felddy** [comment]
I'm glad you figured it out.  I'm going to open a new issue to make the boolean variables less pedantic.  I'm sure that other users will get caught by this the way it is currently implemented. 

I also wanted to make sure you were aware of the optional `FOUNDRY_WORLD` [environment variable](https://github.com/felddy/foundryvtt-docker#optional-variables).
