### ISSUE TITLE
Any way to get access to the app directory from outside the container?

### ISSUE THREAD

**Issue by deurk** [felddy/foundryvtt-docker#60]
# 💬 Questions and Help
Is there a way to incorporate FTP/SFTP/SAMBA/WEBDAV or any other protocol which would allow access to the app directory from outside the container to allow easier work with assets and worlds migrations for example ?

**Comment by felddy** [comment]
All of your assets and worlds should be stored outside the container in the host filesystem.  That is the purpose of the `/data` [volume](https://docs.docker.com/storage/volumes/) that you should be bind mounting: 

https://github.com/felddy/foundryvtt-docker#volumes

Using Docker: 
`--volume /data:<your_data_dir>`

Or in a docker-compose file:
```yml
    volumes:
      - type: bind
        source: <your_data_dir>
        target: /data
```

Foundry will use that volume for all [user data](https://foundryvtt.com/article/configuration/#where-user-data).


If you did manage to store worlds and assets in the container (by not providing a volume mount) you can use the [docker `cp` command](https://docs.docker.com/engine/reference/commandline/cp/) to copy the files out of the container. 

Example:
```console
docker cp foundry_1:/data exported_data
```

Does this answer your question?

**Comment by deurk** [comment]
Thank you for your detailed answer. What I meant was more in the line of having the volume shared outside of the docker host.
I had not thought about it enough before asking the question though, since adding a samba or sftp container sharing the same volume will work for the need.

Thank you for your nice work 👍
