### ISSUE TITLE
Podman support?

### ISSUE THREAD

**Issue by ghost** [felddy/foundryvtt-docker#621]
### Feature description

I would like to add support specifically for podman support in rootless mode.

### Motivation

It is an up and coming container engine that supports rootless mode allowing better security through not running daemons and apps inside root.

### Example

Basically the same as docker, except without needing root and the security implications with that.

### Pitch

Since the motivation I think would be strong enough considering it would be nice to have the segregation of not running as root, that should be a good enough reason.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by formerlyKnownAsLagzilla** [comment]
podman has been docker compatible since 3.0

https://developers.redhat.com/cheat-sheets/podman-cheat-sheet?intcmp=701f20000012ngPAAQ&extIdCarryOver=true&sc_cid=701f2000001OH7EAAW

**Comment by brucetony** [comment]
I am running v10.291 using podman (rootless) without any issues. AFAIK foundry does not require any special root privileges and so it should have full functionality when using podman to build the container.

**Comment by pyrige** [comment]
I have also been running these images on rootless podman for a while now without any issues, FWIW.

**Comment by felddy** [comment]
This is the best type of feature request.  (The ones that require no code changes).  Thank you to the folks that verified the functionality.  

Since it sounds like it is already working I'm going to close this.  If this isn't the case please feel free to reopen it.
