### ISSUE TITLE
"docker-init" not found when attempting to launch container

### ISSUE THREAD

**Issue by gormley-logan** [felddy/foundryvtt-docker#683]
### Bug description

I was recently notified by one of my players that the server I had been hosting using your docker container went offline. After some investigating I discovered no issues with the hardware itself being offline, simply that the docker container was not running. Attempting to run `docker compose up --detach` results in the following error: `Error response from daemon: exec: "docker-init": executable file not found in $PATH`

I have reinstalled docker and docker-compose and I have verified other docker compose containers successfully launch, the issue seems to be specific to this one. 

### Steps to reproduce

- Run a server for a few months
- ???
- Be alerted that it went offline
- Attempt `docker compose up --detach` to boot the container back online
- Receive error  `Error response from daemon: exec: "docker-init": executable file not found in $PATH`

### Expected behavior

I expect that the container would launch despite not changing anything on my end. As far as I am aware no docker or docker compose update was performed prior to the container failing.

### Container metadata

```shell
com.foundryvtt.version = "10.291"
org.opencontainers.image.authors = "markf+github@geekpad.com"
org.opencontainers.image.created = "2023-04-29T19:59:31.910Z"
org.opencontainers.image.description = "An easy-to-deploy Dockerized Foundry Virtual Tabletop server."
org.opencontainers.image.licenses = "MIT"
org.opencontainers.image.revision = "98271566841dbdb086bede336d8885137dcf7550"
org.opencontainers.image.source = "https://github.com/felddy/foundryvtt-docker"
org.opencontainers.image.title = "foundryvtt-docker"
org.opencontainers.image.url = "https://github.com/felddy/foundryvtt-docker"
org.opencontainers.image.vendor = "Geekpad"
org.opencontainers.image.version = "10.291.1"
```

### Relevant log output

```console
[+] Running 0/1
 ⠿ Container foundryvtt-foundry-1  Starting                                                                                                                                                                 0.3s
Error response from daemon: exec: "docker-init": executable file not found in $PATH
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cytec123187** [comment]
I am experiencing the same issue - the issue began on or around 5/15.

**Comment by felddy** [comment]
Thank you for reporting the issue.  Sorry for the delay.
I'll take a look at this later today and see if I can reproduce it.

**Comment by felddy** [comment]
My research leads me to believe that this is probably not an issue with the container but with the Docker installation.  We can still try a few things to test though.  

1. Can you please provide me some information about your Docker installation.  Host OS, etc...
2. Can you post in your `docker-compose.yml` file with and sensitive information redacted.  
3. If you are using the `init: true` clause, try removing it and see if you get a different message from the Docker daemon.  
4. See if a different build of the container behaves differently.  For example, check to see if the nightly build does the same thing: `felddy/foundryvtt:nightly`

Hopefully this can shed a bit more light on the issue.

**Comment by cytec123187** [comment]
Item #3 has resolved the issue for me. I removed the init: true clause from my docker-compose.yml file and was then able to redeploy the container successfully. Thank you for the help!

**Comment by Paisan0** [comment]
Same issue. Commenting out Item 3 resolved the issue instantly. Thank you.

**Comment by felddy** [comment]
@cytec123187 and @Paisan0 , I'm glad you're both back up an running.  When you get a chance could you let me know what your Docker host setup is like?  I'm curious what changed that is making `init` fail now.   What are your host OSs, and versions of your runtimes (`containerd` or `cri-o`).  

Your instances will be fine without the init process, and I'll remove it from the example composition so others don't run into this.

**Comment by Paisan0** [comment]
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu

I'm happy to help, but I'm not sure if this is all you were asking for.

Thank you.

**Comment by felddy** [comment]
I think the information I'm looking for is `containerd --version` and `docker --version`:

```console
➤ containerd --version
containerd github.com/containerd/containerd 1.4.13~ds1 1.4.13~ds1-1~deb11u3

➤ docker --version
Docker version 20.10.5+dfsg1, build 55c4c88
```

**Comment by Paisan0** [comment]
Docker version 20.10.24, build 297e128

No containerd installed, no cri-o installed.

**Comment by cytec123187** [comment]
I am also running Docker version 20.10.24, build 297e128, and I don't have containerd installed.
