### ISSUE TITLE
Add 10.303 image

### ISSUE THREAD

**Issue by cs96and** [felddy/foundryvtt-docker#726]
### Feature description

Foundry recently release v10.303, as the last revision in the v10 line.  Could you add a docker image for it please?

### Motivation

- I've not moved to v11 yet and would like the latest v10 version

### Example

- For people still on v10

### Pitch

- Because you should probably have images of all released versions

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felddy** [comment]
[Release `10.303.0`](https://github.com/felddy/foundryvtt-docker/releases/tag/v10.303.0) is [now building](https://github.com/felddy/foundryvtt-docker/actions/runs/5425593110) and should be available in about 10-15 minutes.

**Comment by cs96and** [comment]
Thanks!
