### ISSUE TITLE
Custom image paths breaking on version update

### ISSUE THREAD

**Issue by amalgamemnon** [felddy/foundryvtt-docker#729]
### Bug description

Updating from v11.302 to v11.304 breaks any custom image paths for icons not appearing in compendiums.

### Steps to reproduce

1. Create a new item directly on a character sheet in v11.302.  Do not select it from a compendium, just create a custom item using the + symbol.
2. Create a new folder within your /data directory called "Homebrew1".
3. Place an image to be used as your item's icon in this folder.
4. In Foundry, select the item, click on the default icon in the upper left, and navigate to the /data/Homebrew1 directory on your data folders.  Then click the "Browse..." button.
5. Select the image you wish to use for the custom icon and update the item.
7. Close the browser window, then update to v11.304.
8. After completing the update, use docker compose up --detach to host Foundry.
9. Open a browser window and re-launch your world.
10. Open the character sheet.  The icon for the created item will have a broken image and the path will have changed.

### Expected behavior

I expect that the image path will not break or change after updating Foundry.

### Container metadata

```shell
The container metadata command doesn't work.  Returns error "template parsing error: template: :1: unexpected "%" in operand".
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felddy** [comment]
Hey @amalgamemnon,

This sounds like an issue with FoundryVTT itself and not this container.   That said, if you could run a couple checks it might help determine the cause:

1. The container does normalize file permissions in the `data` directory at startup.  If you add your custom image, and then restart the container without changing the version to `11.304` does the behavior occur?  This behavior can be disabled with the `CONTAINER_PRESERVE_OWNER` environment variable.  See the [`README`](https://github.com/felddy/foundryvtt-docker#optional-variables) for more information.

1. If you revert back to container version `11.302` from `11.304` does the image icon work again, or is it still broke? 

I didn't see any other reports of a similar issue in the FoundryVTT bug tracker, but you may want to take a look:
- https://github.com/foundryvtt/foundryvtt/issues

**Comment by felddy** [comment]
I just release version `11.305.0` of the container which supports FoundryVTT `11.305`.  Please see if your issue was addressed or persists.  

See:
- https://github.com/felddy/foundryvtt-docker/releases/tag/v11.305.0
- https://foundryvtt.com/releases/11.305

**Comment by amalgamemnon** [comment]
The behavior did not occur when updating from 11.304.0 to 11.305.  I did not change the `CONTAINER_PRESERVE_OWNER` parameter, so whatever you changed worked!

**Comment by felddy** [comment]
The only thing that was changed in the container source was the version of FoundryVTT being installed.  Foundry's release notes had some bullets that could have been relevant.  In any case I'm glad your problem has been solved.  Feel free to reopen this issue if it reoccurs.

See:
- https://github.com/felddy/foundryvtt-docker/commit/71e680887c4fdf9ff55e25d0e8571fd1db1e73c9
- https://foundryvtt.com/releases/11.305
