### ISSUE TITLE
An environment variable to configure the Setup Theme

### ISSUE THREAD

**Issue by BoltsJ** [felddy/foundryvtt-docker#743]
### Feature description

An environment variable to configure the Setup Theme

### Motivation

v11 added css themes for setup, but there's not a way to configure them other than by enabling `CONTAINER_PRESERVE_CONFIG`.

### Example

There are 3 setup themes and the value is stored in the `cssTheme` key in `options.json`
- Foundry Virtual Tabletop: `foundry`
- Classic Fantasy: `fantasy`
- Science Fiction: `scifi`

### Pitch

It would be in line, design-wise with the other env vars.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felddy** [comment]
Yes!  I totally forgot to add this when it was released.  I'll add it soon.  Thanks for the issue.
