### ISSUE TITLE
Freezing before login screen

### ISSUE THREAD

**Issue by BushTrocity** [felddy/foundryvtt-docker#744]
### Bug description

I'm running the newest version of foundry as a docker on unraid. A few people are having connection issues connecting to the site. It freezes before the login screen on a gray page with the game name and version number. In the docker log I see it creating a client session but not doing anything after that. I fresh world and no plugins still cause the issue. The foundry discord was zero help and because I am running it as a docker they couldn't help me.

### Steps to reproduce

Trying to connect to the server in a normal chrome, firefox or edge browser for the ones the issue is affecting doesn't work. I can cause the issue to happen to me if I use a incognito windows in chrome. Here is a screenshot of the console with the error.

![Screenshot 2023-07-30 225113](https://github.com/felddy/foundryvtt-docker/assets/3528732/0d8d3f66-d40a-43ce-8645-c4b69bf010d9)

### Expected behavior

To be able to see the login screen.

### Container metadata

```shell
com.foundryvtt.version = "11.306"
org.opencontainers.image.authors = "markf+github@geekpad.com"
org.opencontainers.image.created = "2023-07-21T16:28:47.154Z"
org.opencontainers.image.description = "An easy-to-deploy Dockerized Foundry Virtual Tabletop server."
org.opencontainers.image.licenses = "MIT"
org.opencontainers.image.revision = "f379bf9645ef353c5a80fae0ad64866d374a2269"
org.opencontainers.image.source = "https://github.com/felddy/foundryvtt-docker"
org.opencontainers.image.title = "foundryvtt-docker"
org.opencontainers.image.url = "https://github.com/felddy/foundryvtt-docker"
org.opencontainers.image.vendor = "Geekpad"
org.opencontainers.image.version = "11.306.0"
```

### Relevant log output

```console
Nothing seems to be erroring or giving me issues in the docker but if you need/want something from the verbose output let me know.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ghost** [comment]
Had the same error. A hard reload of the site (clearing the cache) via CTRL + Shift + R fixed it for me.

**Comment by BushTrocity** [comment]
> Had the same error. A hard reload of the site (clearing the cache) via CTRL + Shift + R fixed it for me.

We tried that and fully resetting the web browser didn't fix it sadly.

I found my issue. It was cloudflare's caching that was breaking it.
Adding a page rule to bypass caching the whole domain and under the speed tab turning off minify for JavaScript. That fixed the issues I was having.

**Comment by ghost** [comment]
Strange. I'm also using Cloudflare and I didn't change those settings you mentioned. Working fine (minus that one time I mentioned) since the beginning of 2022 now.
