### ISSUE TITLE
Unexpected response 429: Too Many Requests

### ISSUE THREAD

**Issue by aep** [felddy/foundryvtt-docker#753]
### Bug description

```
Entrypoint | 2023-08-09 14:45:13 | [info] Starting felddy/foundryvtt container v10.303.0
Entrypoint | 2023-08-09 14:45:13 | [info] No Foundry Virtual Tabletop installation detected.
Entrypoint | 2023-08-09 14:45:13 | [info] Using FOUNDRY_USERNAME and FOUNDRY_PASSWORD to authenticate.
Authenticate | 2023-08-09 14:45:13 | [info] Requesting CSRF tokens from https://foundryvtt.com
Authenticate | 2023-08-09 14:45:14 | [info] Logging in as: laserganz
Authenticate | 2023-08-09 14:45:16 | [info] Successfully logged in as: redacted
Entrypoint | 2023-08-09 14:45:16 | [info] Using authenticated credentials to download release.
hReleaseURL | 2023-08-09 14:45:16 | [info] Fetching S3 pre-signed release URL for build 303...
_ReleaseURL | 2023-08-09 14:45:17 | [warn] Unexpected response 429: Too Many Requests
```

### Steps to reproduce

restart the container in a loop. 

### Expected behavior

i thought the foundry tarball was cached to avoid this exact problem?

```
~ # ls /var/lib/docker/volumes/foundryvtt/_data/container_cache/
downloading.zip       foundryvtt-9.269.zip
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aep** [comment]
ugh, sorry for the noise.
The minor version changed, so of course it re-downloads.

:facepalm:

**Comment by ThiefMaster** [comment]
Actually I don't think this is invalid: Even if the version remains the same (or the correct version is in the container cache), a failure to login and get a download link causes the container to crash.

Instead, it should assume the file in the container cache is valid and try to use that...

**Comment by etriebe** [comment]
This is still happening to me and once I get into this state I don't know how to get out. How have people resolved this?
