### ISSUE TITLE
Support FoundryVTT release 11.308

### ISSUE THREAD

**Issue by uniwars** [felddy/foundryvtt-docker#765]
### Bug description

Hi, I'm trying to update to the last stable version of Foundry but the docker doesn't find 11.308. Is that normal ? I updated only once from 306 to 307 and it worked fine, but there is apparently a desync issue and 308 seems to fix it. My game is pretty much bugged until I can update to 308 and the same update steps I did does not work.

### Steps to reproduce

Update to 11.308

### Expected behavior

Docker updates

### Container metadata

```shell
.
```

### Relevant log output

```console
https://cdn.discordapp.com/attachments/1111088928032837712/1144573033005195314/image.png
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felddy** [comment]
I haven't had a chance to release `11.308` yet.  It should be published shortly.

You can find the container's support releases in the `Releases` section of the repository: https://github.com/felddy/foundryvtt-docker/releases

In most cases you may set the `FOUNDRY_VERSION` [optional environment variable](https://github.com/felddy/foundryvtt-docker#optional-variables) on an existing container to override the version that is installed.  In your case you'd set it to `11.308`.
