### ISSUE TITLE
Setting image to :beta pulled :release version instead

### ISSUE THREAD

**Issue by eclarke12** [felddy/foundryvtt-docker#78]
# 🐛 Bug Report

Possibly I don't understand how the image works, but my assumption was that today (Oct 3, 2020), using `:beta` would pull version 0.7.3

## To Reproduce

- Create container
- Set image to `felddy/foundryvtt-docker:beta`

## Expected behavior

Foundry version 0.7.3 is installed in the container 

## Any helpful log output

Please run this command:

```bash
docker inspect --format='{{range $k, $v := .Config.Labels}}
    {{- printf "%s = \"%s\"\n" $k $v -}} {{end}}' \
    felddy/foundryvtt:latest
```

Paste the results here:

```console

```

Run the container with `CONTAINER_VERBOSE` set to `true`,and paste any useful
log output here:

```console

```

**Comment by eclarke12** [comment]
For a moment I thought this might be caused by having the container cache turned on, but even with it disabled, it is still pulling 0.6.6

**Comment by eclarke12** [comment]
This was a PEBKAC. I duplicated an existing container and missed the `FOUNDRY_VERSION` env flag that was set to `0.6.6` sorry!

**Comment by felddy** [comment]
No probs!  Glad you figured it out.  I'm here to help if things go south again.  Cheers!
