### ISSUE TITLE
Add support for foundry 11.309

### ISSUE THREAD

**Issue by uniwars** [felddy/foundryvtt-docker#792]
### Feature description

Hi, sorry for asking for new release again, but I did a dumb system update which didn't require 11.309 but many modules that now need to be updated to support the new system release require .309 :/

Since it's a minor update I can understand that I screw myself if you skip it.

### Motivation

.

### Example

.

### Pitch

.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jturnley** [comment]
FYI, the new Pathfinder Kingmaker adventure requires 11.309 and it's a pretty hot ticket...

**Comment by felddy** [comment]
I understand.  You can set the `FOUNDRY_VERSION` environment variable to `11.309` on your current container to get the new release of FoundryVTT.  

I am working on disabling the blocking architecture now and trying to get a clean build.  

See:
- https://github.com/felddy/foundryvtt-docker/pull/788#issuecomment-1733769239
- https://github.com/felddy/foundryvtt-docker/issues/794
- https://github.com/felddy/foundryvtt-docker/pull/795
- https://github.com/felddy/npm-hang-test/issues/2

**Comment by felddy** [comment]
- https://github.com/felddy/foundryvtt-docker/discussions/796

**Comment by uniwars** [comment]
Thanks, I will try to do that
v11.311 just released lol

**Comment by felddy** [comment]
Wonderful.  Docker Hub is currently having "ongoing issues" so despite my best efforts this isn't going to plan.  I'll keep an eye on things and try to keep it moving when the universe settles back down.
