### ISSUE TITLE
No backup/snapshot options available

### ISSUE THREAD

**Issue by ericvoshall** [felddy/foundryvtt-docker#801]
### Bug description

Backups and snapshots were released in [Foundry 11.311](https://foundryvtt.com/article/backups), but none of the backup options listed in the knowledge base article are available. I didn't see any references for a new environment variable that needed to be set or anything, so I'm not sure if this is a bug or just not supported for Docker installs.

### Steps to reproduce

Multiple options to perform a backup listed in [knowledge base article](https://foundryvtt.com/article/backups), but an example:

- Right click a world
- Missing "Take Backup" option
- Also missing the backup manager icon in the top right of the setup menu.

### Expected behavior

I expect to be able to make and restore backups and snapshots.

### Container metadata

```shell
com.foundryvtt.version = "11.311"
org.opencontainers.image.authors = "markf+github@geekpad.com"
org.opencontainers.image.created = "2023-09-29T00:03:59.458Z"
org.opencontainers.image.description = "An easy-to-deploy Dockerized Foundry Virtual Tabletop server."
org.opencontainers.image.licenses = "MIT"
org.opencontainers.image.revision = "2fac62dd530713a68bdb4f9650b94600abdb50e3"
org.opencontainers.image.source = "https://github.com/felddy/foundryvtt-docker"
org.opencontainers.image.title = "foundryvtt-docker"
org.opencontainers.image.url = "https://github.com/felddy/foundryvtt-docker"
org.opencontainers.image.vendor = "Geekpad"
org.opencontainers.image.version = "11.311.0"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felddy** [comment]
When I start up the container it immediately starts the "Backups Overview" tour.   The context menus for `Take Backup` and `Manage Backups` are also present.   

What version does the logs show?   You should see: 
```console
FoundryVTT | 2023-10-02 12:02:34 | [info] Running on Node.js - Version 18.18.0
FoundryVTT | 2023-10-02 12:02:34 | [info] Foundry Virtual Tabletop - Version 11 Build 311
``` 

Do you see `Version 11 Build 311` in the bottom of your Foundry setup screen?  
Are you manually overriding the `FOUNDRY_VERSION` environment variable with a previous version? (check the logs for warnings about this).

**Comment by ericvoshall** [comment]
It looks like it was a cache issue - clearing the cache and signing in to the setup menu triggered the tour. Thanks!
