### ISSUE TITLE
Allow backup/world uploads

### ISSUE THREAD

**Issue by david-plugge** [felddy/foundryvtt-docker#816]
### Feature description

It would be nice to directly upload your backups and worlds on a hosted instance rather than doing it manually.

### Motivation

- Easy of use

### Example

A button that opens a modal prompting the user to select a backup file from the file system.

### Pitch

There is a backup system implemented but you can only create and download backups.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felddy** [comment]
Hey @david-plugge .  This sounds like a great feature.  Unfortunately it is not in-scope for this containerization repository.  

I think you should take a look at the [official FoundryVTT repository](https://github.com/foundryvtt/foundryvtt) to see if a similar feature request has already been made.  If it hasn't yet, you should open it there:

- https://github.com/foundryvtt/foundryvtt/issues

**Comment by david-plugge** [comment]
Ouh sorry, thanks for your quick response. I'll open an issue over there.
