### ISSUE TITLE
Automate container_cache cleanup

### ISSUE THREAD

**Issue by madereddy** [felddy/foundryvtt-docker#830]
### Feature description

When updating to the latest version of Foundry, it will download the the latest version as a zip file. That zip file is stored along with older versions. The older versions should be deleted to save space.

### Motivation

-Save space on docker host

### Example

- The container can delete the entire configuration_cache folder and recreate it
- Otherwise the container can see what foundry version is running and delete the versions that are not being used.

### Pitch

- Maintenance proposal to save space on the docker host which will help anyone running on a VPS as those usually have limited space.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by madereddy** [comment]
Created a PR for this: https://github.com/felddy/foundryvtt-docker/pull/840

**Comment by felddy** [comment]
Hi @madereddy,

Firstly, I want to extend a big thank you for your recent pull request. Your initiative and willingness to contribute are greatly valued.

I should have communicated earlier that I had already started working on a similar feature in a separate branch. I've now opened a draft PR with a slightly different approach to cache management. Your insights and review on this would be incredibly beneficial.

When you have a moment, could you please test the `felddy/foundryvtt:improvement-cache-clean` image? You can set the `CONTAINER_CACHE_SIZE` environment variable as per your preference. For instance, setting it to `1` would closely emulate the behavior proposed in your PR.

I'd love to hear your feedback on this implementation. The key difference in this approach is that it's designed as an opt-in feature. We've recognized that several developers and game masters utilize this container for multiple versions of FoundryVTT and for running various instances from the same cache. Ensuring flexibility and optional usage was a crucial aspect of this feature.

Thank you once again for your contribution and looking forward to your thoughts on the draft PR.

**Comment by madereddy** [comment]
Hey @felddy, I was able to pull the image and perform some testing and everything worked out great. Your solution is much more elegant and I did not realize that there were users who wanted to keep the older foundry versions. Thank you for quickly adding this feature.
