### ISSUE TITLE
Missing 10.312 tag

### ISSUE THREAD

**Issue by tradiuz** [felddy/foundryvtt-docker#902]
### Bug description

If you specify 10.312 as the image tag, it will fail to install.  if you specify 10 as the version tag, it will download 10.303.   If you specify a download URL, it will recognize that 312 is different than 303 and re-download every time.

### Steps to reproduce

- use the `image: felddy/foundryvtt:10.312` in a `docker-compose.yml`

### Expected behavior

I expect that it will recognize 10.312 as a valid version.

### Container metadata

```shell
com.foundryvtt.version = "11.315"
org.opencontainers.image.authors = "markf+github@geekpad.com"
org.opencontainers.image.created = "2024-01-05T17:39:23.478Z"
org.opencontainers.image.description = "An easy-to-deploy Dockerized Foundry Virtual Tabletop server."
org.opencontainers.image.licenses = "MIT"
org.opencontainers.image.revision = "18981628b89a04fa780f9faa1657be17aeaeb9b1"
org.opencontainers.image.source = "https://github.com/felddy/foundryvtt-docker"
org.opencontainers.image.title = "foundryvtt-docker"
org.opencontainers.image.url = "https://github.com/felddy/foundryvtt-docker"
org.opencontainers.image.vendor = "Geekpad"
org.opencontainers.image.version = "11.315.1"
```

### Relevant log output

```console
✘ foundry Error0.6s
Error response from daemon: manifest for felddy/foundryvtt:10.312 not found: manifest unknown: manifest unknown
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felddy** [comment]
The last release of the container in the `10` series is [`10.303`](https://github.com/felddy/foundryvtt-docker/releases/tag/v10.303.0).  If you want to use `10.312` you can follow the procedure here:
- https://github.com/felddy/foundryvtt-docker/issues/868#issuecomment-1939130534

Use the `felddy/foundryvtt:release` container and set `FOUNDRY_VERSION` to `10.312`. 

You will see a warning in the logs:
```console
foundry-1  | Entrypoint | 2024-02-25 11:26:44 | [warn] FOUNDRY_VERSION has been manually set and does not match the container's version.
foundry-1  | Entrypoint | 2024-02-25 11:26:44 | [warn] Expected 11.315 but found 10.312
foundry-1  | Entrypoint | 2024-02-25 11:26:44 | [warn] The container may not function properly with this version mismatch.
```

I've tested that this works correctly.   But heed the warning in the comment above and backup your data directory.

See also:
- https://github.com/felddy/foundryvtt-docker/discussions/796
