### ISSUE TITLE
Restarting causes it to download and install again

### ISSUE THREAD

**Issue by pkp24** [felddy/foundryvtt-docker#933]
### Bug description

Every time the docker restarts it doesn't just start, it reinstalls completely. This is annoying because it means I constantly have to authenticate my license and if I restart it too many times it will cause foundry to restrict my access. I feel like it should be checking what version is available and what version is installed and doing a comparison before deciding to download the "update".

### Steps to reproduce

Use unraid and restart the docker.

### Expected behavior

it starts up without a huge wait to reinstall.

### Container metadata

```shell
Couldn't get the command to work, it's the most up to date version on unraid as of 11:43 am EST 4/7/2024
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felddy** [comment]
Thanks for opening this issue.  Since you did not provide the requested logs, or information about the version you are running, I cannot attempt to help solve the issue.  If you are able to provide logs I will be more than happy to help out.
