### ISSUE TITLE
Container not working

### ISSUE THREAD

**Issue by Aiacos** [felddy/foundryvtt-docker#935]
### Bug description

Entrypoint | 2024-04-13 22:59:23 | [info] No Foundry Virtual Tabletop installation detected.
Entrypoint | 2024-04-13 22:59:23 | [info] Using CONTAINER_CACHE: /data/container_cache
Entrypoint | 2024-04-13 22:59:23 | [error] Unable to install Foundry Virtual Tabletop!
Entrypoint | 2024-04-13 22:59:23 | [error] Either set FOUNDRY_RELEASE_URL.
Entrypoint | 2024-04-13 22:59:23 | [error] Or set FOUNDRY_USERNAME and FOUNDRY_PASSWORD.
Entrypoint | 2024-04-13 22:59:23 | [error] Or set CONTAINER_CACHE to a directory containing foundryvtt-11.315.zip

### Steps to reproduce

Run the username/password docker run OR with url gibe the error

### Expected behavior

Running container

### Container metadata

```shell
docker run felddy/foundryvtt:release \
  --env FOUNDRY_RELEASE_URL='https://foundryvtt.s3.amazonaws.com/releases/11.315/FoundryVTT-11.315.zip?AWSAccessKeyId=******************' \
  --publish 30000:30000/tcp \
  --volume /DATA/D&D/00_FoundryVTT:/data
```

### Relevant log output

```console
Entrypoint | 2024-04-13 22:59:23 | [info] No Foundry Virtual Tabletop installation detected.
Entrypoint | 2024-04-13 22:59:23 | [info] Using CONTAINER_CACHE: /data/container_cache
Entrypoint | 2024-04-13 22:59:23 | [error] Unable to install Foundry Virtual Tabletop!
Entrypoint | 2024-04-13 22:59:23 | [error] Either set FOUNDRY_RELEASE_URL.
Entrypoint | 2024-04-13 22:59:23 | [error] Or set FOUNDRY_USERNAME and FOUNDRY_PASSWORD.
Entrypoint | 2024-04-13 22:59:23 | [error] Or set CONTAINER_CACHE to a directory containing foundryvtt-11.315.zip
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felddy** [comment]
It looks like the environment variables are not set correctly.  The ampersand (`&`) in your volume path could be problematic, depending on your shell and filesystem.  

If you can get `CONTAINER_VERBOSE` set to `true` it might shed more light on the problem.  But I suspect that if you are able to do that, you'll also have solved the problem with `FOUNDRY_RELEASE_URL` not being set.

**Comment by Aiacos** [comment]
I dont know if this one is correct but same error

docker run felddy/foundryvtt:release \
  --env FOUNDRY_RELEASE_URL='https://foundryvtt.s3.amazonaws.com/releases/11.315/FoundryVTT-11.315.zip?AWSAccessKeyId=*************' \
  --env CONTAINER_VERBOSE=true \
  --publish 30000:30000/tcp \
  --volume /DATA/foundry_vtt/:/data
Entrypoint | 2024-04-13 23:34:07 | [info] Starting felddy/foundryvtt container v11.315.1
Entrypoint | 2024-04-13 23:34:07 | [info] No Foundry Virtual Tabletop installation detected.
Entrypoint | 2024-04-13 23:34:07 | [info] Using CONTAINER_CACHE: /data/container_cache
Entrypoint | 2024-04-13 23:34:07 | [error] Unable to install Foundry Virtual Tabletop!
Entrypoint | 2024-04-13 23:34:07 | [error] Either set FOUNDRY_RELEASE_URL.
Entrypoint | 2024-04-13 23:34:07 | [error] Or set FOUNDRY_USERNAME and FOUNDRY_PASSWORD.
Entrypoint | 2024-04-13 23:34:07 | [error] Or set CONTAINER_CACHE to a directory containing foundryvtt-11.315.zip

**Comment by felddy** [comment]
You're calling `docker run` incorrectly:

```console
Usage:  docker run [OPTIONS] IMAGE [COMMAND] [ARG...]
```
 
You want the `--env` options to go to `docker`.  The way you are calling it is sending the options as arguments to the container.  

So, in your case, the proper invocation would be:

```console
docker run
--env FOUNDRY_RELEASE_URL='https://foundryvtt.s3.amazonaws.com/releases/11.315/FoundryVTT-11.315.zip?AWSAccessKeyId=*************' \
--env CONTAINER_VERBOSE=true \
--publish 30000:30000/tcp \
--volume /DATA/foundry_vtt/:/data \
felddy/foundryvtt:release
```
