### ISSUE TITLE
Health Check for docker container falsely reports unhealthy when foundryvtt is running with inbuilt https server

### ISSUE THREAD

**Issue by cmbernard333** [felddy/foundryvtt-docker#96]
# 🐛 Bug Report

The health check provided by `check_health.sh` does not provide the correct container status when the container is running using https (not behind nginx or other such server).

Https means setting the paths for both `sslKey` and `sslCert` and using the `inbuilt` ssl server.

## To Reproduce

- Start container using a docker-compose.yml specifying the environment variables for `sslKey` and `sslCert`
- Inspect container using `docker ps <container-id>` or similar command interface such as portainer
![foundryvtt-containers-unhealth-2020-10-25](https://user-images.githubusercontent.com/4392507/97113712-6c77b280-16a9-11eb-8936-58c309e070f6.PNG)

- See the container status is `unhealthy`

## Expected behavior

Expect to see the container status as `healthy` especially when it is idle.

### Checking Health With HTTPS

You can observe the container is actually healthy by getting a shell into the container and running `curl -k --cookie-jar healthcheck-cookiejar.txt --cookie healthcheck-cookiejar.txt --fail https://localhost:30000/api/status` which on the image tag `felddy/foundryvtt-docker:0.7.5` release produces this result `{"version":"0.7.5"}`.

The `-k` argument may not be the best to use from a security standpoint as you might be using a self signed certificate, but this can be worked around by passing the `sslCert` and `sslKey` variables into the `check_health.sh` script if correct https validation is needed to be performed.

## Any helpful log output

Please run this command:

```bash
docker inspect --format='{{range $k, $v := .Config.Labels}}
    {{- printf "%s = \"%s\"\n" $k $v -}} {{end}}' \
    felddy/foundryvtt:latest
```

Paste the results here:

```console
com.docker.compose.config-hash = "8bc8ddd3796576d04e2f1092fbc0dcd2123a3a2316f481fa0f0c94341cefc1e4"
com.docker.compose.container-number = "1"
com.docker.compose.oneoff = "False"
com.docker.compose.project = "foundryvtt"
com.docker.compose.project.config_files = "docker-compose.yml"
com.docker.compose.project.working_dir = "/home/christian/Docker/foundryvtt"
com.docker.compose.service = "foundryvtt"
com.docker.compose.version = "1.27.4"
com.foundryvtt.version = "0.7.5"
org.opencontainers.image.authors = "markf+github@geekpad.com"
org.opencontainers.image.vendor = "Geekpad"

```

Run the container with `CONTAINER_VERBOSE` set to `true`,and paste any useful
log output here:

This shows the container is idle and currently accepting connections

```console
FoundryVTT | 2020-10-25 16:48:19 | [info] License verification succeeded
FoundryVTT | 2020-10-25 16:48:20 | [info] Server started and listening on port 30000
FoundryVTT | 2020-10-25 16:48:30 | [info] Created client session 68xp6fdwr2dmhslhn4xz7htl
FoundryVTT | 2020-10-25 16:48:31 | [info] No core software update is currently available.
FoundryVTT | 2020-10-25 16:53:14 | [info] Created client session w2gv92i94osfp55zdc6gglcm

```

**Comment by cmbernard333** [comment]
This might not be a common scenario is it is better form to run `nginx` in front of foundryvtt, but for those who want to use a simpler setup it's easier to use `sslCert` and `sslKey`.

**Comment by felddy** [comment]
I've pushed up a fix.  CI is currently testing it and building an image.  

When it is done can you try pulling: `felddy/foundryvtt:bugfix-https_healthcheck` and checking to see if this addresses the issue.   The image should be done shortly.  

You should be able to see the progress here: https://github.com/felddy/foundryvtt-docker/runs/1305459308?check_suite_focus=true

**Comment by cmbernard333** [comment]
> 
> 
> I've pushed up a fix. CI is currently testing it and building an image.
> 
> When it is done can you try pulling: `felddy/foundryvtt:bugfix-https_healthcheck` and checking to see if this addresses the issue. The image should be done shortly.
> 
> You should be able to see the progress here: https://github.com/felddy/foundryvtt-docker/runs/1305459308?check_suite_focus=true

Awesome! I'll keep an eye out.

**Comment by felddy** [comment]
@cmbernard333 were you able to test this fix?   
The [image is up on Docker hub](https://hub.docker.com/layers/felddy/foundryvtt/bugfix-https_healthcheck/images/sha256-62d626e81783b4b02f7e7adfbecc1486ec7aaf72f7a2eb26745fd4427c3ea7f4?context=explore&tab=layers).
