### ISSUE TITLE
Generate the initial options.json even if CONTAINER_PRESERVE_CONFIG set to true

### ISSUE THREAD

**Issue by hmqgg** [felddy/foundryvtt-docker#99]
# 🚀 Feature Proposal

https://github.com/felddy/foundryvtt-docker/blob/c780e0f9aafc154fa37bfb7d82624f0368adffba/src/launcher.sh#L22

It only checks `CONTAINER_PRESERVE_CONFIG` as for now, but didn't check if the file `options.json`/`admin.txt` exists. So it won't generate the initial config files if `CONTAINER_PRESERVE_CONFIG` set to true.

I think it's better to also check if the config files exist, else update/generate.

e.g.:
```bash
if [[ "${CONTAINER_PRESERVE_CONFIG:-}" == "true" && -e options.json && -e admin.txt ]]; then
```

## Motivation

It's more convenient to use if generate the initial configs but preserve it form regen without modifying container env var.

## Example

Running with "-e CONTAINER_PRESERVE_CONFIG=true", it generates the initial config files.

After start, modify the `options.json` by FVTT setup panel and the change preserves. 

## Pitch

FVTT docker container related.

**Comment by felddy** [comment]
Awesome.  Thank you!  I actually just coded it up and pushed it up to GitHub.  CI is building  and testing the image from the branch now. 

The image is on Docker Hub now.

If you want to try it out you can pull  `felddy/foundryvtt:improvement-write_config_once` .

**Comment by felddy** [comment]
@hmqgg container `0.7.5+b` has been released and addresses this issue:
https://github.com/felddy/foundryvtt-docker/releases/tag/v0.7.5%2Bb

Please let me know if this feature is working for you as request.
